
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `ColorPosition` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums.ts"
import type * as Prisma from "../internal/prismaNamespace.ts"

/**
 * Model ColorPosition
 * 
 */
export type ColorPositionModel = runtime.Types.Result.DefaultSelection<Prisma.$ColorPositionPayload>

export type AggregateColorPosition = {
  _count: ColorPositionCountAggregateOutputType | null
  _min: ColorPositionMinAggregateOutputType | null
  _max: ColorPositionMaxAggregateOutputType | null
}

export type ColorPositionMinAggregateOutputType = {
  id: string | null
  fabricId: string | null
  colorLayoutId: string | null
  wbNo: string | null
  createdAt: Date | null
  updatedAt: Date | null
}

export type ColorPositionMaxAggregateOutputType = {
  id: string | null
  fabricId: string | null
  colorLayoutId: string | null
  wbNo: string | null
  createdAt: Date | null
  updatedAt: Date | null
}

export type ColorPositionCountAggregateOutputType = {
  id: number
  fabricId: number
  colorLayoutId: number
  fabricContent: number
  wbNo: number
  createdAt: number
  updatedAt: number
  _all: number
}


export type ColorPositionMinAggregateInputType = {
  id?: true
  fabricId?: true
  colorLayoutId?: true
  wbNo?: true
  createdAt?: true
  updatedAt?: true
}

export type ColorPositionMaxAggregateInputType = {
  id?: true
  fabricId?: true
  colorLayoutId?: true
  wbNo?: true
  createdAt?: true
  updatedAt?: true
}

export type ColorPositionCountAggregateInputType = {
  id?: true
  fabricId?: true
  colorLayoutId?: true
  fabricContent?: true
  wbNo?: true
  createdAt?: true
  updatedAt?: true
  _all?: true
}

export type ColorPositionAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which ColorPosition to aggregate.
   */
  where?: Prisma.ColorPositionWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of ColorPositions to fetch.
   */
  orderBy?: Prisma.ColorPositionOrderByWithRelationInput | Prisma.ColorPositionOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.ColorPositionWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` ColorPositions from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` ColorPositions.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned ColorPositions
  **/
  _count?: true | ColorPositionCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: ColorPositionMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: ColorPositionMaxAggregateInputType
}

export type GetColorPositionAggregateType<T extends ColorPositionAggregateArgs> = {
      [P in keyof T & keyof AggregateColorPosition]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateColorPosition[P]>
    : Prisma.GetScalarType<T[P], AggregateColorPosition[P]>
}




export type ColorPositionGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.ColorPositionWhereInput
  orderBy?: Prisma.ColorPositionOrderByWithAggregationInput | Prisma.ColorPositionOrderByWithAggregationInput[]
  by: Prisma.ColorPositionScalarFieldEnum[] | Prisma.ColorPositionScalarFieldEnum
  having?: Prisma.ColorPositionScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: ColorPositionCountAggregateInputType | true
  _min?: ColorPositionMinAggregateInputType
  _max?: ColorPositionMaxAggregateInputType
}

export type ColorPositionGroupByOutputType = {
  id: string
  fabricId: string
  colorLayoutId: string
  fabricContent: runtime.JsonValue | null
  wbNo: string
  createdAt: Date
  updatedAt: Date | null
  _count: ColorPositionCountAggregateOutputType | null
  _min: ColorPositionMinAggregateOutputType | null
  _max: ColorPositionMaxAggregateOutputType | null
}

type GetColorPositionGroupByPayload<T extends ColorPositionGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<ColorPositionGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof ColorPositionGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], ColorPositionGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], ColorPositionGroupByOutputType[P]>
      }
    >
  >



export type ColorPositionWhereInput = {
  AND?: Prisma.ColorPositionWhereInput | Prisma.ColorPositionWhereInput[]
  OR?: Prisma.ColorPositionWhereInput[]
  NOT?: Prisma.ColorPositionWhereInput | Prisma.ColorPositionWhereInput[]
  id?: Prisma.StringFilter<"ColorPosition"> | string
  fabricId?: Prisma.StringFilter<"ColorPosition"> | string
  colorLayoutId?: Prisma.StringFilter<"ColorPosition"> | string
  fabricContent?: Prisma.JsonNullableFilter<"ColorPosition">
  wbNo?: Prisma.StringFilter<"ColorPosition"> | string
  createdAt?: Prisma.DateTimeFilter<"ColorPosition"> | Date | string
  updatedAt?: Prisma.DateTimeNullableFilter<"ColorPosition"> | Date | string | null
  fabric?: Prisma.XOR<Prisma.FabricScalarRelationFilter, Prisma.FabricWhereInput>
  colorLayout?: Prisma.XOR<Prisma.ColorLayoutScalarRelationFilter, Prisma.ColorLayoutWhereInput>
}

export type ColorPositionOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  fabricId?: Prisma.SortOrder
  colorLayoutId?: Prisma.SortOrder
  fabricContent?: Prisma.SortOrderInput | Prisma.SortOrder
  wbNo?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrderInput | Prisma.SortOrder
  fabric?: Prisma.FabricOrderByWithRelationInput
  colorLayout?: Prisma.ColorLayoutOrderByWithRelationInput
}

export type ColorPositionWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  AND?: Prisma.ColorPositionWhereInput | Prisma.ColorPositionWhereInput[]
  OR?: Prisma.ColorPositionWhereInput[]
  NOT?: Prisma.ColorPositionWhereInput | Prisma.ColorPositionWhereInput[]
  fabricId?: Prisma.StringFilter<"ColorPosition"> | string
  colorLayoutId?: Prisma.StringFilter<"ColorPosition"> | string
  fabricContent?: Prisma.JsonNullableFilter<"ColorPosition">
  wbNo?: Prisma.StringFilter<"ColorPosition"> | string
  createdAt?: Prisma.DateTimeFilter<"ColorPosition"> | Date | string
  updatedAt?: Prisma.DateTimeNullableFilter<"ColorPosition"> | Date | string | null
  fabric?: Prisma.XOR<Prisma.FabricScalarRelationFilter, Prisma.FabricWhereInput>
  colorLayout?: Prisma.XOR<Prisma.ColorLayoutScalarRelationFilter, Prisma.ColorLayoutWhereInput>
}, "id">

export type ColorPositionOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  fabricId?: Prisma.SortOrder
  colorLayoutId?: Prisma.SortOrder
  fabricContent?: Prisma.SortOrderInput | Prisma.SortOrder
  wbNo?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrderInput | Prisma.SortOrder
  _count?: Prisma.ColorPositionCountOrderByAggregateInput
  _max?: Prisma.ColorPositionMaxOrderByAggregateInput
  _min?: Prisma.ColorPositionMinOrderByAggregateInput
}

export type ColorPositionScalarWhereWithAggregatesInput = {
  AND?: Prisma.ColorPositionScalarWhereWithAggregatesInput | Prisma.ColorPositionScalarWhereWithAggregatesInput[]
  OR?: Prisma.ColorPositionScalarWhereWithAggregatesInput[]
  NOT?: Prisma.ColorPositionScalarWhereWithAggregatesInput | Prisma.ColorPositionScalarWhereWithAggregatesInput[]
  id?: Prisma.StringWithAggregatesFilter<"ColorPosition"> | string
  fabricId?: Prisma.StringWithAggregatesFilter<"ColorPosition"> | string
  colorLayoutId?: Prisma.StringWithAggregatesFilter<"ColorPosition"> | string
  fabricContent?: Prisma.JsonNullableWithAggregatesFilter<"ColorPosition">
  wbNo?: Prisma.StringWithAggregatesFilter<"ColorPosition"> | string
  createdAt?: Prisma.DateTimeWithAggregatesFilter<"ColorPosition"> | Date | string
  updatedAt?: Prisma.DateTimeNullableWithAggregatesFilter<"ColorPosition"> | Date | string | null
}

export type ColorPositionCreateInput = {
  id?: string
  fabricContent?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  wbNo: string
  createdAt?: Date | string
  updatedAt?: Date | string | null
  fabric: Prisma.FabricCreateNestedOneWithoutColorPositionsInput
  colorLayout: Prisma.ColorLayoutCreateNestedOneWithoutColorPositionsInput
}

export type ColorPositionUncheckedCreateInput = {
  id?: string
  fabricId: string
  colorLayoutId: string
  fabricContent?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  wbNo: string
  createdAt?: Date | string
  updatedAt?: Date | string | null
}

export type ColorPositionUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  fabricContent?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  wbNo?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  fabric?: Prisma.FabricUpdateOneRequiredWithoutColorPositionsNestedInput
  colorLayout?: Prisma.ColorLayoutUpdateOneRequiredWithoutColorPositionsNestedInput
}

export type ColorPositionUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  fabricId?: Prisma.StringFieldUpdateOperationsInput | string
  colorLayoutId?: Prisma.StringFieldUpdateOperationsInput | string
  fabricContent?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  wbNo?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
}

export type ColorPositionCreateManyInput = {
  id?: string
  fabricId: string
  colorLayoutId: string
  fabricContent?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  wbNo: string
  createdAt?: Date | string
  updatedAt?: Date | string | null
}

export type ColorPositionUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  fabricContent?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  wbNo?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
}

export type ColorPositionUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  fabricId?: Prisma.StringFieldUpdateOperationsInput | string
  colorLayoutId?: Prisma.StringFieldUpdateOperationsInput | string
  fabricContent?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  wbNo?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
}

export type ColorPositionListRelationFilter = {
  every?: Prisma.ColorPositionWhereInput
  some?: Prisma.ColorPositionWhereInput
  none?: Prisma.ColorPositionWhereInput
}

export type ColorPositionOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type ColorPositionCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  fabricId?: Prisma.SortOrder
  colorLayoutId?: Prisma.SortOrder
  fabricContent?: Prisma.SortOrder
  wbNo?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type ColorPositionMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  fabricId?: Prisma.SortOrder
  colorLayoutId?: Prisma.SortOrder
  wbNo?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type ColorPositionMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  fabricId?: Prisma.SortOrder
  colorLayoutId?: Prisma.SortOrder
  wbNo?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type ColorPositionCreateNestedManyWithoutColorLayoutInput = {
  create?: Prisma.XOR<Prisma.ColorPositionCreateWithoutColorLayoutInput, Prisma.ColorPositionUncheckedCreateWithoutColorLayoutInput> | Prisma.ColorPositionCreateWithoutColorLayoutInput[] | Prisma.ColorPositionUncheckedCreateWithoutColorLayoutInput[]
  connectOrCreate?: Prisma.ColorPositionCreateOrConnectWithoutColorLayoutInput | Prisma.ColorPositionCreateOrConnectWithoutColorLayoutInput[]
  createMany?: Prisma.ColorPositionCreateManyColorLayoutInputEnvelope
  connect?: Prisma.ColorPositionWhereUniqueInput | Prisma.ColorPositionWhereUniqueInput[]
}

export type ColorPositionUncheckedCreateNestedManyWithoutColorLayoutInput = {
  create?: Prisma.XOR<Prisma.ColorPositionCreateWithoutColorLayoutInput, Prisma.ColorPositionUncheckedCreateWithoutColorLayoutInput> | Prisma.ColorPositionCreateWithoutColorLayoutInput[] | Prisma.ColorPositionUncheckedCreateWithoutColorLayoutInput[]
  connectOrCreate?: Prisma.ColorPositionCreateOrConnectWithoutColorLayoutInput | Prisma.ColorPositionCreateOrConnectWithoutColorLayoutInput[]
  createMany?: Prisma.ColorPositionCreateManyColorLayoutInputEnvelope
  connect?: Prisma.ColorPositionWhereUniqueInput | Prisma.ColorPositionWhereUniqueInput[]
}

export type ColorPositionUpdateManyWithoutColorLayoutNestedInput = {
  create?: Prisma.XOR<Prisma.ColorPositionCreateWithoutColorLayoutInput, Prisma.ColorPositionUncheckedCreateWithoutColorLayoutInput> | Prisma.ColorPositionCreateWithoutColorLayoutInput[] | Prisma.ColorPositionUncheckedCreateWithoutColorLayoutInput[]
  connectOrCreate?: Prisma.ColorPositionCreateOrConnectWithoutColorLayoutInput | Prisma.ColorPositionCreateOrConnectWithoutColorLayoutInput[]
  upsert?: Prisma.ColorPositionUpsertWithWhereUniqueWithoutColorLayoutInput | Prisma.ColorPositionUpsertWithWhereUniqueWithoutColorLayoutInput[]
  createMany?: Prisma.ColorPositionCreateManyColorLayoutInputEnvelope
  set?: Prisma.ColorPositionWhereUniqueInput | Prisma.ColorPositionWhereUniqueInput[]
  disconnect?: Prisma.ColorPositionWhereUniqueInput | Prisma.ColorPositionWhereUniqueInput[]
  delete?: Prisma.ColorPositionWhereUniqueInput | Prisma.ColorPositionWhereUniqueInput[]
  connect?: Prisma.ColorPositionWhereUniqueInput | Prisma.ColorPositionWhereUniqueInput[]
  update?: Prisma.ColorPositionUpdateWithWhereUniqueWithoutColorLayoutInput | Prisma.ColorPositionUpdateWithWhereUniqueWithoutColorLayoutInput[]
  updateMany?: Prisma.ColorPositionUpdateManyWithWhereWithoutColorLayoutInput | Prisma.ColorPositionUpdateManyWithWhereWithoutColorLayoutInput[]
  deleteMany?: Prisma.ColorPositionScalarWhereInput | Prisma.ColorPositionScalarWhereInput[]
}

export type ColorPositionUncheckedUpdateManyWithoutColorLayoutNestedInput = {
  create?: Prisma.XOR<Prisma.ColorPositionCreateWithoutColorLayoutInput, Prisma.ColorPositionUncheckedCreateWithoutColorLayoutInput> | Prisma.ColorPositionCreateWithoutColorLayoutInput[] | Prisma.ColorPositionUncheckedCreateWithoutColorLayoutInput[]
  connectOrCreate?: Prisma.ColorPositionCreateOrConnectWithoutColorLayoutInput | Prisma.ColorPositionCreateOrConnectWithoutColorLayoutInput[]
  upsert?: Prisma.ColorPositionUpsertWithWhereUniqueWithoutColorLayoutInput | Prisma.ColorPositionUpsertWithWhereUniqueWithoutColorLayoutInput[]
  createMany?: Prisma.ColorPositionCreateManyColorLayoutInputEnvelope
  set?: Prisma.ColorPositionWhereUniqueInput | Prisma.ColorPositionWhereUniqueInput[]
  disconnect?: Prisma.ColorPositionWhereUniqueInput | Prisma.ColorPositionWhereUniqueInput[]
  delete?: Prisma.ColorPositionWhereUniqueInput | Prisma.ColorPositionWhereUniqueInput[]
  connect?: Prisma.ColorPositionWhereUniqueInput | Prisma.ColorPositionWhereUniqueInput[]
  update?: Prisma.ColorPositionUpdateWithWhereUniqueWithoutColorLayoutInput | Prisma.ColorPositionUpdateWithWhereUniqueWithoutColorLayoutInput[]
  updateMany?: Prisma.ColorPositionUpdateManyWithWhereWithoutColorLayoutInput | Prisma.ColorPositionUpdateManyWithWhereWithoutColorLayoutInput[]
  deleteMany?: Prisma.ColorPositionScalarWhereInput | Prisma.ColorPositionScalarWhereInput[]
}

export type ColorPositionCreateNestedManyWithoutFabricInput = {
  create?: Prisma.XOR<Prisma.ColorPositionCreateWithoutFabricInput, Prisma.ColorPositionUncheckedCreateWithoutFabricInput> | Prisma.ColorPositionCreateWithoutFabricInput[] | Prisma.ColorPositionUncheckedCreateWithoutFabricInput[]
  connectOrCreate?: Prisma.ColorPositionCreateOrConnectWithoutFabricInput | Prisma.ColorPositionCreateOrConnectWithoutFabricInput[]
  createMany?: Prisma.ColorPositionCreateManyFabricInputEnvelope
  connect?: Prisma.ColorPositionWhereUniqueInput | Prisma.ColorPositionWhereUniqueInput[]
}

export type ColorPositionUncheckedCreateNestedManyWithoutFabricInput = {
  create?: Prisma.XOR<Prisma.ColorPositionCreateWithoutFabricInput, Prisma.ColorPositionUncheckedCreateWithoutFabricInput> | Prisma.ColorPositionCreateWithoutFabricInput[] | Prisma.ColorPositionUncheckedCreateWithoutFabricInput[]
  connectOrCreate?: Prisma.ColorPositionCreateOrConnectWithoutFabricInput | Prisma.ColorPositionCreateOrConnectWithoutFabricInput[]
  createMany?: Prisma.ColorPositionCreateManyFabricInputEnvelope
  connect?: Prisma.ColorPositionWhereUniqueInput | Prisma.ColorPositionWhereUniqueInput[]
}

export type ColorPositionUpdateManyWithoutFabricNestedInput = {
  create?: Prisma.XOR<Prisma.ColorPositionCreateWithoutFabricInput, Prisma.ColorPositionUncheckedCreateWithoutFabricInput> | Prisma.ColorPositionCreateWithoutFabricInput[] | Prisma.ColorPositionUncheckedCreateWithoutFabricInput[]
  connectOrCreate?: Prisma.ColorPositionCreateOrConnectWithoutFabricInput | Prisma.ColorPositionCreateOrConnectWithoutFabricInput[]
  upsert?: Prisma.ColorPositionUpsertWithWhereUniqueWithoutFabricInput | Prisma.ColorPositionUpsertWithWhereUniqueWithoutFabricInput[]
  createMany?: Prisma.ColorPositionCreateManyFabricInputEnvelope
  set?: Prisma.ColorPositionWhereUniqueInput | Prisma.ColorPositionWhereUniqueInput[]
  disconnect?: Prisma.ColorPositionWhereUniqueInput | Prisma.ColorPositionWhereUniqueInput[]
  delete?: Prisma.ColorPositionWhereUniqueInput | Prisma.ColorPositionWhereUniqueInput[]
  connect?: Prisma.ColorPositionWhereUniqueInput | Prisma.ColorPositionWhereUniqueInput[]
  update?: Prisma.ColorPositionUpdateWithWhereUniqueWithoutFabricInput | Prisma.ColorPositionUpdateWithWhereUniqueWithoutFabricInput[]
  updateMany?: Prisma.ColorPositionUpdateManyWithWhereWithoutFabricInput | Prisma.ColorPositionUpdateManyWithWhereWithoutFabricInput[]
  deleteMany?: Prisma.ColorPositionScalarWhereInput | Prisma.ColorPositionScalarWhereInput[]
}

export type ColorPositionUncheckedUpdateManyWithoutFabricNestedInput = {
  create?: Prisma.XOR<Prisma.ColorPositionCreateWithoutFabricInput, Prisma.ColorPositionUncheckedCreateWithoutFabricInput> | Prisma.ColorPositionCreateWithoutFabricInput[] | Prisma.ColorPositionUncheckedCreateWithoutFabricInput[]
  connectOrCreate?: Prisma.ColorPositionCreateOrConnectWithoutFabricInput | Prisma.ColorPositionCreateOrConnectWithoutFabricInput[]
  upsert?: Prisma.ColorPositionUpsertWithWhereUniqueWithoutFabricInput | Prisma.ColorPositionUpsertWithWhereUniqueWithoutFabricInput[]
  createMany?: Prisma.ColorPositionCreateManyFabricInputEnvelope
  set?: Prisma.ColorPositionWhereUniqueInput | Prisma.ColorPositionWhereUniqueInput[]
  disconnect?: Prisma.ColorPositionWhereUniqueInput | Prisma.ColorPositionWhereUniqueInput[]
  delete?: Prisma.ColorPositionWhereUniqueInput | Prisma.ColorPositionWhereUniqueInput[]
  connect?: Prisma.ColorPositionWhereUniqueInput | Prisma.ColorPositionWhereUniqueInput[]
  update?: Prisma.ColorPositionUpdateWithWhereUniqueWithoutFabricInput | Prisma.ColorPositionUpdateWithWhereUniqueWithoutFabricInput[]
  updateMany?: Prisma.ColorPositionUpdateManyWithWhereWithoutFabricInput | Prisma.ColorPositionUpdateManyWithWhereWithoutFabricInput[]
  deleteMany?: Prisma.ColorPositionScalarWhereInput | Prisma.ColorPositionScalarWhereInput[]
}

export type ColorPositionCreateWithoutColorLayoutInput = {
  id?: string
  fabricContent?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  wbNo: string
  createdAt?: Date | string
  updatedAt?: Date | string | null
  fabric: Prisma.FabricCreateNestedOneWithoutColorPositionsInput
}

export type ColorPositionUncheckedCreateWithoutColorLayoutInput = {
  id?: string
  fabricId: string
  fabricContent?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  wbNo: string
  createdAt?: Date | string
  updatedAt?: Date | string | null
}

export type ColorPositionCreateOrConnectWithoutColorLayoutInput = {
  where: Prisma.ColorPositionWhereUniqueInput
  create: Prisma.XOR<Prisma.ColorPositionCreateWithoutColorLayoutInput, Prisma.ColorPositionUncheckedCreateWithoutColorLayoutInput>
}

export type ColorPositionCreateManyColorLayoutInputEnvelope = {
  data: Prisma.ColorPositionCreateManyColorLayoutInput | Prisma.ColorPositionCreateManyColorLayoutInput[]
  skipDuplicates?: boolean
}

export type ColorPositionUpsertWithWhereUniqueWithoutColorLayoutInput = {
  where: Prisma.ColorPositionWhereUniqueInput
  update: Prisma.XOR<Prisma.ColorPositionUpdateWithoutColorLayoutInput, Prisma.ColorPositionUncheckedUpdateWithoutColorLayoutInput>
  create: Prisma.XOR<Prisma.ColorPositionCreateWithoutColorLayoutInput, Prisma.ColorPositionUncheckedCreateWithoutColorLayoutInput>
}

export type ColorPositionUpdateWithWhereUniqueWithoutColorLayoutInput = {
  where: Prisma.ColorPositionWhereUniqueInput
  data: Prisma.XOR<Prisma.ColorPositionUpdateWithoutColorLayoutInput, Prisma.ColorPositionUncheckedUpdateWithoutColorLayoutInput>
}

export type ColorPositionUpdateManyWithWhereWithoutColorLayoutInput = {
  where: Prisma.ColorPositionScalarWhereInput
  data: Prisma.XOR<Prisma.ColorPositionUpdateManyMutationInput, Prisma.ColorPositionUncheckedUpdateManyWithoutColorLayoutInput>
}

export type ColorPositionScalarWhereInput = {
  AND?: Prisma.ColorPositionScalarWhereInput | Prisma.ColorPositionScalarWhereInput[]
  OR?: Prisma.ColorPositionScalarWhereInput[]
  NOT?: Prisma.ColorPositionScalarWhereInput | Prisma.ColorPositionScalarWhereInput[]
  id?: Prisma.StringFilter<"ColorPosition"> | string
  fabricId?: Prisma.StringFilter<"ColorPosition"> | string
  colorLayoutId?: Prisma.StringFilter<"ColorPosition"> | string
  fabricContent?: Prisma.JsonNullableFilter<"ColorPosition">
  wbNo?: Prisma.StringFilter<"ColorPosition"> | string
  createdAt?: Prisma.DateTimeFilter<"ColorPosition"> | Date | string
  updatedAt?: Prisma.DateTimeNullableFilter<"ColorPosition"> | Date | string | null
}

export type ColorPositionCreateWithoutFabricInput = {
  id?: string
  fabricContent?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  wbNo: string
  createdAt?: Date | string
  updatedAt?: Date | string | null
  colorLayout: Prisma.ColorLayoutCreateNestedOneWithoutColorPositionsInput
}

export type ColorPositionUncheckedCreateWithoutFabricInput = {
  id?: string
  colorLayoutId: string
  fabricContent?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  wbNo: string
  createdAt?: Date | string
  updatedAt?: Date | string | null
}

export type ColorPositionCreateOrConnectWithoutFabricInput = {
  where: Prisma.ColorPositionWhereUniqueInput
  create: Prisma.XOR<Prisma.ColorPositionCreateWithoutFabricInput, Prisma.ColorPositionUncheckedCreateWithoutFabricInput>
}

export type ColorPositionCreateManyFabricInputEnvelope = {
  data: Prisma.ColorPositionCreateManyFabricInput | Prisma.ColorPositionCreateManyFabricInput[]
  skipDuplicates?: boolean
}

export type ColorPositionUpsertWithWhereUniqueWithoutFabricInput = {
  where: Prisma.ColorPositionWhereUniqueInput
  update: Prisma.XOR<Prisma.ColorPositionUpdateWithoutFabricInput, Prisma.ColorPositionUncheckedUpdateWithoutFabricInput>
  create: Prisma.XOR<Prisma.ColorPositionCreateWithoutFabricInput, Prisma.ColorPositionUncheckedCreateWithoutFabricInput>
}

export type ColorPositionUpdateWithWhereUniqueWithoutFabricInput = {
  where: Prisma.ColorPositionWhereUniqueInput
  data: Prisma.XOR<Prisma.ColorPositionUpdateWithoutFabricInput, Prisma.ColorPositionUncheckedUpdateWithoutFabricInput>
}

export type ColorPositionUpdateManyWithWhereWithoutFabricInput = {
  where: Prisma.ColorPositionScalarWhereInput
  data: Prisma.XOR<Prisma.ColorPositionUpdateManyMutationInput, Prisma.ColorPositionUncheckedUpdateManyWithoutFabricInput>
}

export type ColorPositionCreateManyColorLayoutInput = {
  id?: string
  fabricId: string
  fabricContent?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  wbNo: string
  createdAt?: Date | string
  updatedAt?: Date | string | null
}

export type ColorPositionUpdateWithoutColorLayoutInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  fabricContent?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  wbNo?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  fabric?: Prisma.FabricUpdateOneRequiredWithoutColorPositionsNestedInput
}

export type ColorPositionUncheckedUpdateWithoutColorLayoutInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  fabricId?: Prisma.StringFieldUpdateOperationsInput | string
  fabricContent?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  wbNo?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
}

export type ColorPositionUncheckedUpdateManyWithoutColorLayoutInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  fabricId?: Prisma.StringFieldUpdateOperationsInput | string
  fabricContent?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  wbNo?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
}

export type ColorPositionCreateManyFabricInput = {
  id?: string
  colorLayoutId: string
  fabricContent?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  wbNo: string
  createdAt?: Date | string
  updatedAt?: Date | string | null
}

export type ColorPositionUpdateWithoutFabricInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  fabricContent?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  wbNo?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  colorLayout?: Prisma.ColorLayoutUpdateOneRequiredWithoutColorPositionsNestedInput
}

export type ColorPositionUncheckedUpdateWithoutFabricInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  colorLayoutId?: Prisma.StringFieldUpdateOperationsInput | string
  fabricContent?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  wbNo?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
}

export type ColorPositionUncheckedUpdateManyWithoutFabricInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  colorLayoutId?: Prisma.StringFieldUpdateOperationsInput | string
  fabricContent?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  wbNo?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
}



export type ColorPositionSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  fabricId?: boolean
  colorLayoutId?: boolean
  fabricContent?: boolean
  wbNo?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  fabric?: boolean | Prisma.FabricDefaultArgs<ExtArgs>
  colorLayout?: boolean | Prisma.ColorLayoutDefaultArgs<ExtArgs>
}, ExtArgs["result"]["colorPosition"]>

export type ColorPositionSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  fabricId?: boolean
  colorLayoutId?: boolean
  fabricContent?: boolean
  wbNo?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  fabric?: boolean | Prisma.FabricDefaultArgs<ExtArgs>
  colorLayout?: boolean | Prisma.ColorLayoutDefaultArgs<ExtArgs>
}, ExtArgs["result"]["colorPosition"]>

export type ColorPositionSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  fabricId?: boolean
  colorLayoutId?: boolean
  fabricContent?: boolean
  wbNo?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  fabric?: boolean | Prisma.FabricDefaultArgs<ExtArgs>
  colorLayout?: boolean | Prisma.ColorLayoutDefaultArgs<ExtArgs>
}, ExtArgs["result"]["colorPosition"]>

export type ColorPositionSelectScalar = {
  id?: boolean
  fabricId?: boolean
  colorLayoutId?: boolean
  fabricContent?: boolean
  wbNo?: boolean
  createdAt?: boolean
  updatedAt?: boolean
}

export type ColorPositionOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "fabricId" | "colorLayoutId" | "fabricContent" | "wbNo" | "createdAt" | "updatedAt", ExtArgs["result"]["colorPosition"]>
export type ColorPositionInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  fabric?: boolean | Prisma.FabricDefaultArgs<ExtArgs>
  colorLayout?: boolean | Prisma.ColorLayoutDefaultArgs<ExtArgs>
}
export type ColorPositionIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  fabric?: boolean | Prisma.FabricDefaultArgs<ExtArgs>
  colorLayout?: boolean | Prisma.ColorLayoutDefaultArgs<ExtArgs>
}
export type ColorPositionIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  fabric?: boolean | Prisma.FabricDefaultArgs<ExtArgs>
  colorLayout?: boolean | Prisma.ColorLayoutDefaultArgs<ExtArgs>
}

export type $ColorPositionPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "ColorPosition"
  objects: {
    fabric: Prisma.$FabricPayload<ExtArgs>
    colorLayout: Prisma.$ColorLayoutPayload<ExtArgs>
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    fabricId: string
    colorLayoutId: string
    fabricContent: runtime.JsonValue | null
    wbNo: string
    createdAt: Date
    updatedAt: Date | null
  }, ExtArgs["result"]["colorPosition"]>
  composites: {}
}

export type ColorPositionGetPayload<S extends boolean | null | undefined | ColorPositionDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$ColorPositionPayload, S>

export type ColorPositionCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<ColorPositionFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: ColorPositionCountAggregateInputType | true
  }

export interface ColorPositionDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['ColorPosition'], meta: { name: 'ColorPosition' } }
  /**
   * Find zero or one ColorPosition that matches the filter.
   * @param {ColorPositionFindUniqueArgs} args - Arguments to find a ColorPosition
   * @example
   * // Get one ColorPosition
   * const colorPosition = await prisma.colorPosition.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends ColorPositionFindUniqueArgs>(args: Prisma.SelectSubset<T, ColorPositionFindUniqueArgs<ExtArgs>>): Prisma.Prisma__ColorPositionClient<runtime.Types.Result.GetResult<Prisma.$ColorPositionPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one ColorPosition that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {ColorPositionFindUniqueOrThrowArgs} args - Arguments to find a ColorPosition
   * @example
   * // Get one ColorPosition
   * const colorPosition = await prisma.colorPosition.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends ColorPositionFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, ColorPositionFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__ColorPositionClient<runtime.Types.Result.GetResult<Prisma.$ColorPositionPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first ColorPosition that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ColorPositionFindFirstArgs} args - Arguments to find a ColorPosition
   * @example
   * // Get one ColorPosition
   * const colorPosition = await prisma.colorPosition.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends ColorPositionFindFirstArgs>(args?: Prisma.SelectSubset<T, ColorPositionFindFirstArgs<ExtArgs>>): Prisma.Prisma__ColorPositionClient<runtime.Types.Result.GetResult<Prisma.$ColorPositionPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first ColorPosition that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ColorPositionFindFirstOrThrowArgs} args - Arguments to find a ColorPosition
   * @example
   * // Get one ColorPosition
   * const colorPosition = await prisma.colorPosition.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends ColorPositionFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, ColorPositionFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__ColorPositionClient<runtime.Types.Result.GetResult<Prisma.$ColorPositionPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more ColorPositions that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ColorPositionFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all ColorPositions
   * const colorPositions = await prisma.colorPosition.findMany()
   * 
   * // Get first 10 ColorPositions
   * const colorPositions = await prisma.colorPosition.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const colorPositionWithIdOnly = await prisma.colorPosition.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends ColorPositionFindManyArgs>(args?: Prisma.SelectSubset<T, ColorPositionFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$ColorPositionPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a ColorPosition.
   * @param {ColorPositionCreateArgs} args - Arguments to create a ColorPosition.
   * @example
   * // Create one ColorPosition
   * const ColorPosition = await prisma.colorPosition.create({
   *   data: {
   *     // ... data to create a ColorPosition
   *   }
   * })
   * 
   */
  create<T extends ColorPositionCreateArgs>(args: Prisma.SelectSubset<T, ColorPositionCreateArgs<ExtArgs>>): Prisma.Prisma__ColorPositionClient<runtime.Types.Result.GetResult<Prisma.$ColorPositionPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many ColorPositions.
   * @param {ColorPositionCreateManyArgs} args - Arguments to create many ColorPositions.
   * @example
   * // Create many ColorPositions
   * const colorPosition = await prisma.colorPosition.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends ColorPositionCreateManyArgs>(args?: Prisma.SelectSubset<T, ColorPositionCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many ColorPositions and returns the data saved in the database.
   * @param {ColorPositionCreateManyAndReturnArgs} args - Arguments to create many ColorPositions.
   * @example
   * // Create many ColorPositions
   * const colorPosition = await prisma.colorPosition.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many ColorPositions and only return the `id`
   * const colorPositionWithIdOnly = await prisma.colorPosition.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends ColorPositionCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, ColorPositionCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$ColorPositionPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a ColorPosition.
   * @param {ColorPositionDeleteArgs} args - Arguments to delete one ColorPosition.
   * @example
   * // Delete one ColorPosition
   * const ColorPosition = await prisma.colorPosition.delete({
   *   where: {
   *     // ... filter to delete one ColorPosition
   *   }
   * })
   * 
   */
  delete<T extends ColorPositionDeleteArgs>(args: Prisma.SelectSubset<T, ColorPositionDeleteArgs<ExtArgs>>): Prisma.Prisma__ColorPositionClient<runtime.Types.Result.GetResult<Prisma.$ColorPositionPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one ColorPosition.
   * @param {ColorPositionUpdateArgs} args - Arguments to update one ColorPosition.
   * @example
   * // Update one ColorPosition
   * const colorPosition = await prisma.colorPosition.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends ColorPositionUpdateArgs>(args: Prisma.SelectSubset<T, ColorPositionUpdateArgs<ExtArgs>>): Prisma.Prisma__ColorPositionClient<runtime.Types.Result.GetResult<Prisma.$ColorPositionPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more ColorPositions.
   * @param {ColorPositionDeleteManyArgs} args - Arguments to filter ColorPositions to delete.
   * @example
   * // Delete a few ColorPositions
   * const { count } = await prisma.colorPosition.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends ColorPositionDeleteManyArgs>(args?: Prisma.SelectSubset<T, ColorPositionDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more ColorPositions.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ColorPositionUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many ColorPositions
   * const colorPosition = await prisma.colorPosition.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends ColorPositionUpdateManyArgs>(args: Prisma.SelectSubset<T, ColorPositionUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more ColorPositions and returns the data updated in the database.
   * @param {ColorPositionUpdateManyAndReturnArgs} args - Arguments to update many ColorPositions.
   * @example
   * // Update many ColorPositions
   * const colorPosition = await prisma.colorPosition.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more ColorPositions and only return the `id`
   * const colorPositionWithIdOnly = await prisma.colorPosition.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends ColorPositionUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, ColorPositionUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$ColorPositionPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one ColorPosition.
   * @param {ColorPositionUpsertArgs} args - Arguments to update or create a ColorPosition.
   * @example
   * // Update or create a ColorPosition
   * const colorPosition = await prisma.colorPosition.upsert({
   *   create: {
   *     // ... data to create a ColorPosition
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the ColorPosition we want to update
   *   }
   * })
   */
  upsert<T extends ColorPositionUpsertArgs>(args: Prisma.SelectSubset<T, ColorPositionUpsertArgs<ExtArgs>>): Prisma.Prisma__ColorPositionClient<runtime.Types.Result.GetResult<Prisma.$ColorPositionPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of ColorPositions.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ColorPositionCountArgs} args - Arguments to filter ColorPositions to count.
   * @example
   * // Count the number of ColorPositions
   * const count = await prisma.colorPosition.count({
   *   where: {
   *     // ... the filter for the ColorPositions we want to count
   *   }
   * })
  **/
  count<T extends ColorPositionCountArgs>(
    args?: Prisma.Subset<T, ColorPositionCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], ColorPositionCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a ColorPosition.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ColorPositionAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends ColorPositionAggregateArgs>(args: Prisma.Subset<T, ColorPositionAggregateArgs>): Prisma.PrismaPromise<GetColorPositionAggregateType<T>>

  /**
   * Group by ColorPosition.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ColorPositionGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends ColorPositionGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: ColorPositionGroupByArgs['orderBy'] }
      : { orderBy?: ColorPositionGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, ColorPositionGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetColorPositionGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the ColorPosition model
 */
readonly fields: ColorPositionFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for ColorPosition.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__ColorPositionClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  fabric<T extends Prisma.FabricDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.FabricDefaultArgs<ExtArgs>>): Prisma.Prisma__FabricClient<runtime.Types.Result.GetResult<Prisma.$FabricPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  colorLayout<T extends Prisma.ColorLayoutDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.ColorLayoutDefaultArgs<ExtArgs>>): Prisma.Prisma__ColorLayoutClient<runtime.Types.Result.GetResult<Prisma.$ColorLayoutPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the ColorPosition model
 */
export interface ColorPositionFieldRefs {
  readonly id: Prisma.FieldRef<"ColorPosition", 'String'>
  readonly fabricId: Prisma.FieldRef<"ColorPosition", 'String'>
  readonly colorLayoutId: Prisma.FieldRef<"ColorPosition", 'String'>
  readonly fabricContent: Prisma.FieldRef<"ColorPosition", 'Json'>
  readonly wbNo: Prisma.FieldRef<"ColorPosition", 'String'>
  readonly createdAt: Prisma.FieldRef<"ColorPosition", 'DateTime'>
  readonly updatedAt: Prisma.FieldRef<"ColorPosition", 'DateTime'>
}
    

// Custom InputTypes
/**
 * ColorPosition findUnique
 */
export type ColorPositionFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ColorPosition
   */
  select?: Prisma.ColorPositionSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ColorPosition
   */
  omit?: Prisma.ColorPositionOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ColorPositionInclude<ExtArgs> | null
  /**
   * Filter, which ColorPosition to fetch.
   */
  where: Prisma.ColorPositionWhereUniqueInput
}

/**
 * ColorPosition findUniqueOrThrow
 */
export type ColorPositionFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ColorPosition
   */
  select?: Prisma.ColorPositionSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ColorPosition
   */
  omit?: Prisma.ColorPositionOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ColorPositionInclude<ExtArgs> | null
  /**
   * Filter, which ColorPosition to fetch.
   */
  where: Prisma.ColorPositionWhereUniqueInput
}

/**
 * ColorPosition findFirst
 */
export type ColorPositionFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ColorPosition
   */
  select?: Prisma.ColorPositionSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ColorPosition
   */
  omit?: Prisma.ColorPositionOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ColorPositionInclude<ExtArgs> | null
  /**
   * Filter, which ColorPosition to fetch.
   */
  where?: Prisma.ColorPositionWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of ColorPositions to fetch.
   */
  orderBy?: Prisma.ColorPositionOrderByWithRelationInput | Prisma.ColorPositionOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for ColorPositions.
   */
  cursor?: Prisma.ColorPositionWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` ColorPositions from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` ColorPositions.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of ColorPositions.
   */
  distinct?: Prisma.ColorPositionScalarFieldEnum | Prisma.ColorPositionScalarFieldEnum[]
}

/**
 * ColorPosition findFirstOrThrow
 */
export type ColorPositionFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ColorPosition
   */
  select?: Prisma.ColorPositionSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ColorPosition
   */
  omit?: Prisma.ColorPositionOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ColorPositionInclude<ExtArgs> | null
  /**
   * Filter, which ColorPosition to fetch.
   */
  where?: Prisma.ColorPositionWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of ColorPositions to fetch.
   */
  orderBy?: Prisma.ColorPositionOrderByWithRelationInput | Prisma.ColorPositionOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for ColorPositions.
   */
  cursor?: Prisma.ColorPositionWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` ColorPositions from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` ColorPositions.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of ColorPositions.
   */
  distinct?: Prisma.ColorPositionScalarFieldEnum | Prisma.ColorPositionScalarFieldEnum[]
}

/**
 * ColorPosition findMany
 */
export type ColorPositionFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ColorPosition
   */
  select?: Prisma.ColorPositionSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ColorPosition
   */
  omit?: Prisma.ColorPositionOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ColorPositionInclude<ExtArgs> | null
  /**
   * Filter, which ColorPositions to fetch.
   */
  where?: Prisma.ColorPositionWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of ColorPositions to fetch.
   */
  orderBy?: Prisma.ColorPositionOrderByWithRelationInput | Prisma.ColorPositionOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing ColorPositions.
   */
  cursor?: Prisma.ColorPositionWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` ColorPositions from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` ColorPositions.
   */
  skip?: number
  distinct?: Prisma.ColorPositionScalarFieldEnum | Prisma.ColorPositionScalarFieldEnum[]
}

/**
 * ColorPosition create
 */
export type ColorPositionCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ColorPosition
   */
  select?: Prisma.ColorPositionSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ColorPosition
   */
  omit?: Prisma.ColorPositionOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ColorPositionInclude<ExtArgs> | null
  /**
   * The data needed to create a ColorPosition.
   */
  data: Prisma.XOR<Prisma.ColorPositionCreateInput, Prisma.ColorPositionUncheckedCreateInput>
}

/**
 * ColorPosition createMany
 */
export type ColorPositionCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many ColorPositions.
   */
  data: Prisma.ColorPositionCreateManyInput | Prisma.ColorPositionCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * ColorPosition createManyAndReturn
 */
export type ColorPositionCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ColorPosition
   */
  select?: Prisma.ColorPositionSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the ColorPosition
   */
  omit?: Prisma.ColorPositionOmit<ExtArgs> | null
  /**
   * The data used to create many ColorPositions.
   */
  data: Prisma.ColorPositionCreateManyInput | Prisma.ColorPositionCreateManyInput[]
  skipDuplicates?: boolean
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ColorPositionIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * ColorPosition update
 */
export type ColorPositionUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ColorPosition
   */
  select?: Prisma.ColorPositionSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ColorPosition
   */
  omit?: Prisma.ColorPositionOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ColorPositionInclude<ExtArgs> | null
  /**
   * The data needed to update a ColorPosition.
   */
  data: Prisma.XOR<Prisma.ColorPositionUpdateInput, Prisma.ColorPositionUncheckedUpdateInput>
  /**
   * Choose, which ColorPosition to update.
   */
  where: Prisma.ColorPositionWhereUniqueInput
}

/**
 * ColorPosition updateMany
 */
export type ColorPositionUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update ColorPositions.
   */
  data: Prisma.XOR<Prisma.ColorPositionUpdateManyMutationInput, Prisma.ColorPositionUncheckedUpdateManyInput>
  /**
   * Filter which ColorPositions to update
   */
  where?: Prisma.ColorPositionWhereInput
  /**
   * Limit how many ColorPositions to update.
   */
  limit?: number
}

/**
 * ColorPosition updateManyAndReturn
 */
export type ColorPositionUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ColorPosition
   */
  select?: Prisma.ColorPositionSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the ColorPosition
   */
  omit?: Prisma.ColorPositionOmit<ExtArgs> | null
  /**
   * The data used to update ColorPositions.
   */
  data: Prisma.XOR<Prisma.ColorPositionUpdateManyMutationInput, Prisma.ColorPositionUncheckedUpdateManyInput>
  /**
   * Filter which ColorPositions to update
   */
  where?: Prisma.ColorPositionWhereInput
  /**
   * Limit how many ColorPositions to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ColorPositionIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * ColorPosition upsert
 */
export type ColorPositionUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ColorPosition
   */
  select?: Prisma.ColorPositionSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ColorPosition
   */
  omit?: Prisma.ColorPositionOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ColorPositionInclude<ExtArgs> | null
  /**
   * The filter to search for the ColorPosition to update in case it exists.
   */
  where: Prisma.ColorPositionWhereUniqueInput
  /**
   * In case the ColorPosition found by the `where` argument doesn't exist, create a new ColorPosition with this data.
   */
  create: Prisma.XOR<Prisma.ColorPositionCreateInput, Prisma.ColorPositionUncheckedCreateInput>
  /**
   * In case the ColorPosition was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.ColorPositionUpdateInput, Prisma.ColorPositionUncheckedUpdateInput>
}

/**
 * ColorPosition delete
 */
export type ColorPositionDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ColorPosition
   */
  select?: Prisma.ColorPositionSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ColorPosition
   */
  omit?: Prisma.ColorPositionOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ColorPositionInclude<ExtArgs> | null
  /**
   * Filter which ColorPosition to delete.
   */
  where: Prisma.ColorPositionWhereUniqueInput
}

/**
 * ColorPosition deleteMany
 */
export type ColorPositionDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which ColorPositions to delete
   */
  where?: Prisma.ColorPositionWhereInput
  /**
   * Limit how many ColorPositions to delete.
   */
  limit?: number
}

/**
 * ColorPosition without action
 */
export type ColorPositionDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ColorPosition
   */
  select?: Prisma.ColorPositionSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ColorPosition
   */
  omit?: Prisma.ColorPositionOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ColorPositionInclude<ExtArgs> | null
}
