
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `FabricConstruction` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums.ts"
import type * as Prisma from "../internal/prismaNamespace.ts"

/**
 * Model FabricConstruction
 * 
 */
export type FabricConstructionModel = runtime.Types.Result.DefaultSelection<Prisma.$FabricConstructionPayload>

export type AggregateFabricConstruction = {
  _count: FabricConstructionCountAggregateOutputType | null
  _avg: FabricConstructionAvgAggregateOutputType | null
  _sum: FabricConstructionSumAggregateOutputType | null
  _min: FabricConstructionMinAggregateOutputType | null
  _max: FabricConstructionMaxAggregateOutputType | null
}

export type FabricConstructionAvgAggregateOutputType = {
  rollCount: number | null
  coneCount: number | null
  sectionCount: number | null
  sectionLength: number | null
  beamWidth: runtime.Decimal | null
  spareEnds: number | null
  beamingLoss: number | null
}

export type FabricConstructionSumAggregateOutputType = {
  rollCount: number | null
  coneCount: number | null
  sectionCount: number | null
  sectionLength: number | null
  beamWidth: runtime.Decimal | null
  spareEnds: number | null
  beamingLoss: number | null
}

export type FabricConstructionMinAggregateOutputType = {
  id: string | null
  fabricSpecId: string | null
  rollCount: number | null
  warpingMachine: $Enums.WbMachineType | null
  coneCount: number | null
  sectionCount: number | null
  sectionLength: number | null
  beamWidth: runtime.Decimal | null
  spareEnds: number | null
  beamingLoss: number | null
  createdAt: Date | null
  updatedAt: Date | null
}

export type FabricConstructionMaxAggregateOutputType = {
  id: string | null
  fabricSpecId: string | null
  rollCount: number | null
  warpingMachine: $Enums.WbMachineType | null
  coneCount: number | null
  sectionCount: number | null
  sectionLength: number | null
  beamWidth: runtime.Decimal | null
  spareEnds: number | null
  beamingLoss: number | null
  createdAt: Date | null
  updatedAt: Date | null
}

export type FabricConstructionCountAggregateOutputType = {
  id: number
  fabricSpecId: number
  rollCount: number
  warpingMachine: number
  coneCount: number
  sectionCount: number
  sectionLength: number
  beamWidth: number
  spareEnds: number
  beamingLoss: number
  createdAt: number
  updatedAt: number
  _all: number
}


export type FabricConstructionAvgAggregateInputType = {
  rollCount?: true
  coneCount?: true
  sectionCount?: true
  sectionLength?: true
  beamWidth?: true
  spareEnds?: true
  beamingLoss?: true
}

export type FabricConstructionSumAggregateInputType = {
  rollCount?: true
  coneCount?: true
  sectionCount?: true
  sectionLength?: true
  beamWidth?: true
  spareEnds?: true
  beamingLoss?: true
}

export type FabricConstructionMinAggregateInputType = {
  id?: true
  fabricSpecId?: true
  rollCount?: true
  warpingMachine?: true
  coneCount?: true
  sectionCount?: true
  sectionLength?: true
  beamWidth?: true
  spareEnds?: true
  beamingLoss?: true
  createdAt?: true
  updatedAt?: true
}

export type FabricConstructionMaxAggregateInputType = {
  id?: true
  fabricSpecId?: true
  rollCount?: true
  warpingMachine?: true
  coneCount?: true
  sectionCount?: true
  sectionLength?: true
  beamWidth?: true
  spareEnds?: true
  beamingLoss?: true
  createdAt?: true
  updatedAt?: true
}

export type FabricConstructionCountAggregateInputType = {
  id?: true
  fabricSpecId?: true
  rollCount?: true
  warpingMachine?: true
  coneCount?: true
  sectionCount?: true
  sectionLength?: true
  beamWidth?: true
  spareEnds?: true
  beamingLoss?: true
  createdAt?: true
  updatedAt?: true
  _all?: true
}

export type FabricConstructionAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which FabricConstruction to aggregate.
   */
  where?: Prisma.FabricConstructionWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of FabricConstructions to fetch.
   */
  orderBy?: Prisma.FabricConstructionOrderByWithRelationInput | Prisma.FabricConstructionOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.FabricConstructionWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` FabricConstructions from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` FabricConstructions.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned FabricConstructions
  **/
  _count?: true | FabricConstructionCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to average
  **/
  _avg?: FabricConstructionAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to sum
  **/
  _sum?: FabricConstructionSumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: FabricConstructionMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: FabricConstructionMaxAggregateInputType
}

export type GetFabricConstructionAggregateType<T extends FabricConstructionAggregateArgs> = {
      [P in keyof T & keyof AggregateFabricConstruction]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateFabricConstruction[P]>
    : Prisma.GetScalarType<T[P], AggregateFabricConstruction[P]>
}




export type FabricConstructionGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.FabricConstructionWhereInput
  orderBy?: Prisma.FabricConstructionOrderByWithAggregationInput | Prisma.FabricConstructionOrderByWithAggregationInput[]
  by: Prisma.FabricConstructionScalarFieldEnum[] | Prisma.FabricConstructionScalarFieldEnum
  having?: Prisma.FabricConstructionScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: FabricConstructionCountAggregateInputType | true
  _avg?: FabricConstructionAvgAggregateInputType
  _sum?: FabricConstructionSumAggregateInputType
  _min?: FabricConstructionMinAggregateInputType
  _max?: FabricConstructionMaxAggregateInputType
}

export type FabricConstructionGroupByOutputType = {
  id: string
  fabricSpecId: string
  rollCount: number
  warpingMachine: $Enums.WbMachineType
  coneCount: number
  sectionCount: number
  sectionLength: number
  beamWidth: runtime.Decimal
  spareEnds: number
  beamingLoss: number | null
  createdAt: Date
  updatedAt: Date | null
  _count: FabricConstructionCountAggregateOutputType | null
  _avg: FabricConstructionAvgAggregateOutputType | null
  _sum: FabricConstructionSumAggregateOutputType | null
  _min: FabricConstructionMinAggregateOutputType | null
  _max: FabricConstructionMaxAggregateOutputType | null
}

export type GetFabricConstructionGroupByPayload<T extends FabricConstructionGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<FabricConstructionGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof FabricConstructionGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], FabricConstructionGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], FabricConstructionGroupByOutputType[P]>
      }
    >
  >



export type FabricConstructionWhereInput = {
  AND?: Prisma.FabricConstructionWhereInput | Prisma.FabricConstructionWhereInput[]
  OR?: Prisma.FabricConstructionWhereInput[]
  NOT?: Prisma.FabricConstructionWhereInput | Prisma.FabricConstructionWhereInput[]
  id?: Prisma.StringFilter<"FabricConstruction"> | string
  fabricSpecId?: Prisma.StringFilter<"FabricConstruction"> | string
  rollCount?: Prisma.IntFilter<"FabricConstruction"> | number
  warpingMachine?: Prisma.EnumWbMachineTypeFilter<"FabricConstruction"> | $Enums.WbMachineType
  coneCount?: Prisma.IntFilter<"FabricConstruction"> | number
  sectionCount?: Prisma.IntFilter<"FabricConstruction"> | number
  sectionLength?: Prisma.IntFilter<"FabricConstruction"> | number
  beamWidth?: Prisma.DecimalFilter<"FabricConstruction"> | runtime.Decimal | runtime.DecimalJsLike | number | string
  spareEnds?: Prisma.IntFilter<"FabricConstruction"> | number
  beamingLoss?: Prisma.IntNullableFilter<"FabricConstruction"> | number | null
  createdAt?: Prisma.DateTimeFilter<"FabricConstruction"> | Date | string
  updatedAt?: Prisma.DateTimeNullableFilter<"FabricConstruction"> | Date | string | null
  fabricSpec?: Prisma.XOR<Prisma.FabricSpecScalarRelationFilter, Prisma.FabricSpecWhereInput>
}

export type FabricConstructionOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  fabricSpecId?: Prisma.SortOrder
  rollCount?: Prisma.SortOrder
  warpingMachine?: Prisma.SortOrder
  coneCount?: Prisma.SortOrder
  sectionCount?: Prisma.SortOrder
  sectionLength?: Prisma.SortOrder
  beamWidth?: Prisma.SortOrder
  spareEnds?: Prisma.SortOrder
  beamingLoss?: Prisma.SortOrderInput | Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrderInput | Prisma.SortOrder
  fabricSpec?: Prisma.FabricSpecOrderByWithRelationInput
}

export type FabricConstructionWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  AND?: Prisma.FabricConstructionWhereInput | Prisma.FabricConstructionWhereInput[]
  OR?: Prisma.FabricConstructionWhereInput[]
  NOT?: Prisma.FabricConstructionWhereInput | Prisma.FabricConstructionWhereInput[]
  fabricSpecId?: Prisma.StringFilter<"FabricConstruction"> | string
  rollCount?: Prisma.IntFilter<"FabricConstruction"> | number
  warpingMachine?: Prisma.EnumWbMachineTypeFilter<"FabricConstruction"> | $Enums.WbMachineType
  coneCount?: Prisma.IntFilter<"FabricConstruction"> | number
  sectionCount?: Prisma.IntFilter<"FabricConstruction"> | number
  sectionLength?: Prisma.IntFilter<"FabricConstruction"> | number
  beamWidth?: Prisma.DecimalFilter<"FabricConstruction"> | runtime.Decimal | runtime.DecimalJsLike | number | string
  spareEnds?: Prisma.IntFilter<"FabricConstruction"> | number
  beamingLoss?: Prisma.IntNullableFilter<"FabricConstruction"> | number | null
  createdAt?: Prisma.DateTimeFilter<"FabricConstruction"> | Date | string
  updatedAt?: Prisma.DateTimeNullableFilter<"FabricConstruction"> | Date | string | null
  fabricSpec?: Prisma.XOR<Prisma.FabricSpecScalarRelationFilter, Prisma.FabricSpecWhereInput>
}, "id">

export type FabricConstructionOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  fabricSpecId?: Prisma.SortOrder
  rollCount?: Prisma.SortOrder
  warpingMachine?: Prisma.SortOrder
  coneCount?: Prisma.SortOrder
  sectionCount?: Prisma.SortOrder
  sectionLength?: Prisma.SortOrder
  beamWidth?: Prisma.SortOrder
  spareEnds?: Prisma.SortOrder
  beamingLoss?: Prisma.SortOrderInput | Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrderInput | Prisma.SortOrder
  _count?: Prisma.FabricConstructionCountOrderByAggregateInput
  _avg?: Prisma.FabricConstructionAvgOrderByAggregateInput
  _max?: Prisma.FabricConstructionMaxOrderByAggregateInput
  _min?: Prisma.FabricConstructionMinOrderByAggregateInput
  _sum?: Prisma.FabricConstructionSumOrderByAggregateInput
}

export type FabricConstructionScalarWhereWithAggregatesInput = {
  AND?: Prisma.FabricConstructionScalarWhereWithAggregatesInput | Prisma.FabricConstructionScalarWhereWithAggregatesInput[]
  OR?: Prisma.FabricConstructionScalarWhereWithAggregatesInput[]
  NOT?: Prisma.FabricConstructionScalarWhereWithAggregatesInput | Prisma.FabricConstructionScalarWhereWithAggregatesInput[]
  id?: Prisma.StringWithAggregatesFilter<"FabricConstruction"> | string
  fabricSpecId?: Prisma.StringWithAggregatesFilter<"FabricConstruction"> | string
  rollCount?: Prisma.IntWithAggregatesFilter<"FabricConstruction"> | number
  warpingMachine?: Prisma.EnumWbMachineTypeWithAggregatesFilter<"FabricConstruction"> | $Enums.WbMachineType
  coneCount?: Prisma.IntWithAggregatesFilter<"FabricConstruction"> | number
  sectionCount?: Prisma.IntWithAggregatesFilter<"FabricConstruction"> | number
  sectionLength?: Prisma.IntWithAggregatesFilter<"FabricConstruction"> | number
  beamWidth?: Prisma.DecimalWithAggregatesFilter<"FabricConstruction"> | runtime.Decimal | runtime.DecimalJsLike | number | string
  spareEnds?: Prisma.IntWithAggregatesFilter<"FabricConstruction"> | number
  beamingLoss?: Prisma.IntNullableWithAggregatesFilter<"FabricConstruction"> | number | null
  createdAt?: Prisma.DateTimeWithAggregatesFilter<"FabricConstruction"> | Date | string
  updatedAt?: Prisma.DateTimeNullableWithAggregatesFilter<"FabricConstruction"> | Date | string | null
}

export type FabricConstructionCreateInput = {
  id?: string
  rollCount: number
  warpingMachine: $Enums.WbMachineType
  coneCount: number
  sectionCount: number
  sectionLength: number
  beamWidth: runtime.Decimal | runtime.DecimalJsLike | number | string
  spareEnds: number
  beamingLoss?: number | null
  createdAt?: Date | string
  updatedAt?: Date | string | null
  fabricSpec: Prisma.FabricSpecCreateNestedOneWithoutFabricConstructionsInput
}

export type FabricConstructionUncheckedCreateInput = {
  id?: string
  fabricSpecId: string
  rollCount: number
  warpingMachine: $Enums.WbMachineType
  coneCount: number
  sectionCount: number
  sectionLength: number
  beamWidth: runtime.Decimal | runtime.DecimalJsLike | number | string
  spareEnds: number
  beamingLoss?: number | null
  createdAt?: Date | string
  updatedAt?: Date | string | null
}

export type FabricConstructionUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  rollCount?: Prisma.IntFieldUpdateOperationsInput | number
  warpingMachine?: Prisma.EnumWbMachineTypeFieldUpdateOperationsInput | $Enums.WbMachineType
  coneCount?: Prisma.IntFieldUpdateOperationsInput | number
  sectionCount?: Prisma.IntFieldUpdateOperationsInput | number
  sectionLength?: Prisma.IntFieldUpdateOperationsInput | number
  beamWidth?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  spareEnds?: Prisma.IntFieldUpdateOperationsInput | number
  beamingLoss?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  fabricSpec?: Prisma.FabricSpecUpdateOneRequiredWithoutFabricConstructionsNestedInput
}

export type FabricConstructionUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  fabricSpecId?: Prisma.StringFieldUpdateOperationsInput | string
  rollCount?: Prisma.IntFieldUpdateOperationsInput | number
  warpingMachine?: Prisma.EnumWbMachineTypeFieldUpdateOperationsInput | $Enums.WbMachineType
  coneCount?: Prisma.IntFieldUpdateOperationsInput | number
  sectionCount?: Prisma.IntFieldUpdateOperationsInput | number
  sectionLength?: Prisma.IntFieldUpdateOperationsInput | number
  beamWidth?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  spareEnds?: Prisma.IntFieldUpdateOperationsInput | number
  beamingLoss?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
}

export type FabricConstructionCreateManyInput = {
  id?: string
  fabricSpecId: string
  rollCount: number
  warpingMachine: $Enums.WbMachineType
  coneCount: number
  sectionCount: number
  sectionLength: number
  beamWidth: runtime.Decimal | runtime.DecimalJsLike | number | string
  spareEnds: number
  beamingLoss?: number | null
  createdAt?: Date | string
  updatedAt?: Date | string | null
}

export type FabricConstructionUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  rollCount?: Prisma.IntFieldUpdateOperationsInput | number
  warpingMachine?: Prisma.EnumWbMachineTypeFieldUpdateOperationsInput | $Enums.WbMachineType
  coneCount?: Prisma.IntFieldUpdateOperationsInput | number
  sectionCount?: Prisma.IntFieldUpdateOperationsInput | number
  sectionLength?: Prisma.IntFieldUpdateOperationsInput | number
  beamWidth?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  spareEnds?: Prisma.IntFieldUpdateOperationsInput | number
  beamingLoss?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
}

export type FabricConstructionUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  fabricSpecId?: Prisma.StringFieldUpdateOperationsInput | string
  rollCount?: Prisma.IntFieldUpdateOperationsInput | number
  warpingMachine?: Prisma.EnumWbMachineTypeFieldUpdateOperationsInput | $Enums.WbMachineType
  coneCount?: Prisma.IntFieldUpdateOperationsInput | number
  sectionCount?: Prisma.IntFieldUpdateOperationsInput | number
  sectionLength?: Prisma.IntFieldUpdateOperationsInput | number
  beamWidth?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  spareEnds?: Prisma.IntFieldUpdateOperationsInput | number
  beamingLoss?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
}

export type FabricConstructionListRelationFilter = {
  every?: Prisma.FabricConstructionWhereInput
  some?: Prisma.FabricConstructionWhereInput
  none?: Prisma.FabricConstructionWhereInput
}

export type FabricConstructionOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type FabricConstructionCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  fabricSpecId?: Prisma.SortOrder
  rollCount?: Prisma.SortOrder
  warpingMachine?: Prisma.SortOrder
  coneCount?: Prisma.SortOrder
  sectionCount?: Prisma.SortOrder
  sectionLength?: Prisma.SortOrder
  beamWidth?: Prisma.SortOrder
  spareEnds?: Prisma.SortOrder
  beamingLoss?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type FabricConstructionAvgOrderByAggregateInput = {
  rollCount?: Prisma.SortOrder
  coneCount?: Prisma.SortOrder
  sectionCount?: Prisma.SortOrder
  sectionLength?: Prisma.SortOrder
  beamWidth?: Prisma.SortOrder
  spareEnds?: Prisma.SortOrder
  beamingLoss?: Prisma.SortOrder
}

export type FabricConstructionMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  fabricSpecId?: Prisma.SortOrder
  rollCount?: Prisma.SortOrder
  warpingMachine?: Prisma.SortOrder
  coneCount?: Prisma.SortOrder
  sectionCount?: Prisma.SortOrder
  sectionLength?: Prisma.SortOrder
  beamWidth?: Prisma.SortOrder
  spareEnds?: Prisma.SortOrder
  beamingLoss?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type FabricConstructionMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  fabricSpecId?: Prisma.SortOrder
  rollCount?: Prisma.SortOrder
  warpingMachine?: Prisma.SortOrder
  coneCount?: Prisma.SortOrder
  sectionCount?: Prisma.SortOrder
  sectionLength?: Prisma.SortOrder
  beamWidth?: Prisma.SortOrder
  spareEnds?: Prisma.SortOrder
  beamingLoss?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type FabricConstructionSumOrderByAggregateInput = {
  rollCount?: Prisma.SortOrder
  coneCount?: Prisma.SortOrder
  sectionCount?: Prisma.SortOrder
  sectionLength?: Prisma.SortOrder
  beamWidth?: Prisma.SortOrder
  spareEnds?: Prisma.SortOrder
  beamingLoss?: Prisma.SortOrder
}

export type FabricConstructionCreateNestedManyWithoutFabricSpecInput = {
  create?: Prisma.XOR<Prisma.FabricConstructionCreateWithoutFabricSpecInput, Prisma.FabricConstructionUncheckedCreateWithoutFabricSpecInput> | Prisma.FabricConstructionCreateWithoutFabricSpecInput[] | Prisma.FabricConstructionUncheckedCreateWithoutFabricSpecInput[]
  connectOrCreate?: Prisma.FabricConstructionCreateOrConnectWithoutFabricSpecInput | Prisma.FabricConstructionCreateOrConnectWithoutFabricSpecInput[]
  createMany?: Prisma.FabricConstructionCreateManyFabricSpecInputEnvelope
  connect?: Prisma.FabricConstructionWhereUniqueInput | Prisma.FabricConstructionWhereUniqueInput[]
}

export type FabricConstructionUncheckedCreateNestedManyWithoutFabricSpecInput = {
  create?: Prisma.XOR<Prisma.FabricConstructionCreateWithoutFabricSpecInput, Prisma.FabricConstructionUncheckedCreateWithoutFabricSpecInput> | Prisma.FabricConstructionCreateWithoutFabricSpecInput[] | Prisma.FabricConstructionUncheckedCreateWithoutFabricSpecInput[]
  connectOrCreate?: Prisma.FabricConstructionCreateOrConnectWithoutFabricSpecInput | Prisma.FabricConstructionCreateOrConnectWithoutFabricSpecInput[]
  createMany?: Prisma.FabricConstructionCreateManyFabricSpecInputEnvelope
  connect?: Prisma.FabricConstructionWhereUniqueInput | Prisma.FabricConstructionWhereUniqueInput[]
}

export type FabricConstructionUpdateManyWithoutFabricSpecNestedInput = {
  create?: Prisma.XOR<Prisma.FabricConstructionCreateWithoutFabricSpecInput, Prisma.FabricConstructionUncheckedCreateWithoutFabricSpecInput> | Prisma.FabricConstructionCreateWithoutFabricSpecInput[] | Prisma.FabricConstructionUncheckedCreateWithoutFabricSpecInput[]
  connectOrCreate?: Prisma.FabricConstructionCreateOrConnectWithoutFabricSpecInput | Prisma.FabricConstructionCreateOrConnectWithoutFabricSpecInput[]
  upsert?: Prisma.FabricConstructionUpsertWithWhereUniqueWithoutFabricSpecInput | Prisma.FabricConstructionUpsertWithWhereUniqueWithoutFabricSpecInput[]
  createMany?: Prisma.FabricConstructionCreateManyFabricSpecInputEnvelope
  set?: Prisma.FabricConstructionWhereUniqueInput | Prisma.FabricConstructionWhereUniqueInput[]
  disconnect?: Prisma.FabricConstructionWhereUniqueInput | Prisma.FabricConstructionWhereUniqueInput[]
  delete?: Prisma.FabricConstructionWhereUniqueInput | Prisma.FabricConstructionWhereUniqueInput[]
  connect?: Prisma.FabricConstructionWhereUniqueInput | Prisma.FabricConstructionWhereUniqueInput[]
  update?: Prisma.FabricConstructionUpdateWithWhereUniqueWithoutFabricSpecInput | Prisma.FabricConstructionUpdateWithWhereUniqueWithoutFabricSpecInput[]
  updateMany?: Prisma.FabricConstructionUpdateManyWithWhereWithoutFabricSpecInput | Prisma.FabricConstructionUpdateManyWithWhereWithoutFabricSpecInput[]
  deleteMany?: Prisma.FabricConstructionScalarWhereInput | Prisma.FabricConstructionScalarWhereInput[]
}

export type FabricConstructionUncheckedUpdateManyWithoutFabricSpecNestedInput = {
  create?: Prisma.XOR<Prisma.FabricConstructionCreateWithoutFabricSpecInput, Prisma.FabricConstructionUncheckedCreateWithoutFabricSpecInput> | Prisma.FabricConstructionCreateWithoutFabricSpecInput[] | Prisma.FabricConstructionUncheckedCreateWithoutFabricSpecInput[]
  connectOrCreate?: Prisma.FabricConstructionCreateOrConnectWithoutFabricSpecInput | Prisma.FabricConstructionCreateOrConnectWithoutFabricSpecInput[]
  upsert?: Prisma.FabricConstructionUpsertWithWhereUniqueWithoutFabricSpecInput | Prisma.FabricConstructionUpsertWithWhereUniqueWithoutFabricSpecInput[]
  createMany?: Prisma.FabricConstructionCreateManyFabricSpecInputEnvelope
  set?: Prisma.FabricConstructionWhereUniqueInput | Prisma.FabricConstructionWhereUniqueInput[]
  disconnect?: Prisma.FabricConstructionWhereUniqueInput | Prisma.FabricConstructionWhereUniqueInput[]
  delete?: Prisma.FabricConstructionWhereUniqueInput | Prisma.FabricConstructionWhereUniqueInput[]
  connect?: Prisma.FabricConstructionWhereUniqueInput | Prisma.FabricConstructionWhereUniqueInput[]
  update?: Prisma.FabricConstructionUpdateWithWhereUniqueWithoutFabricSpecInput | Prisma.FabricConstructionUpdateWithWhereUniqueWithoutFabricSpecInput[]
  updateMany?: Prisma.FabricConstructionUpdateManyWithWhereWithoutFabricSpecInput | Prisma.FabricConstructionUpdateManyWithWhereWithoutFabricSpecInput[]
  deleteMany?: Prisma.FabricConstructionScalarWhereInput | Prisma.FabricConstructionScalarWhereInput[]
}

export type EnumWbMachineTypeFieldUpdateOperationsInput = {
  set?: $Enums.WbMachineType
}

export type FabricConstructionCreateWithoutFabricSpecInput = {
  id?: string
  rollCount: number
  warpingMachine: $Enums.WbMachineType
  coneCount: number
  sectionCount: number
  sectionLength: number
  beamWidth: runtime.Decimal | runtime.DecimalJsLike | number | string
  spareEnds: number
  beamingLoss?: number | null
  createdAt?: Date | string
  updatedAt?: Date | string | null
}

export type FabricConstructionUncheckedCreateWithoutFabricSpecInput = {
  id?: string
  rollCount: number
  warpingMachine: $Enums.WbMachineType
  coneCount: number
  sectionCount: number
  sectionLength: number
  beamWidth: runtime.Decimal | runtime.DecimalJsLike | number | string
  spareEnds: number
  beamingLoss?: number | null
  createdAt?: Date | string
  updatedAt?: Date | string | null
}

export type FabricConstructionCreateOrConnectWithoutFabricSpecInput = {
  where: Prisma.FabricConstructionWhereUniqueInput
  create: Prisma.XOR<Prisma.FabricConstructionCreateWithoutFabricSpecInput, Prisma.FabricConstructionUncheckedCreateWithoutFabricSpecInput>
}

export type FabricConstructionCreateManyFabricSpecInputEnvelope = {
  data: Prisma.FabricConstructionCreateManyFabricSpecInput | Prisma.FabricConstructionCreateManyFabricSpecInput[]
  skipDuplicates?: boolean
}

export type FabricConstructionUpsertWithWhereUniqueWithoutFabricSpecInput = {
  where: Prisma.FabricConstructionWhereUniqueInput
  update: Prisma.XOR<Prisma.FabricConstructionUpdateWithoutFabricSpecInput, Prisma.FabricConstructionUncheckedUpdateWithoutFabricSpecInput>
  create: Prisma.XOR<Prisma.FabricConstructionCreateWithoutFabricSpecInput, Prisma.FabricConstructionUncheckedCreateWithoutFabricSpecInput>
}

export type FabricConstructionUpdateWithWhereUniqueWithoutFabricSpecInput = {
  where: Prisma.FabricConstructionWhereUniqueInput
  data: Prisma.XOR<Prisma.FabricConstructionUpdateWithoutFabricSpecInput, Prisma.FabricConstructionUncheckedUpdateWithoutFabricSpecInput>
}

export type FabricConstructionUpdateManyWithWhereWithoutFabricSpecInput = {
  where: Prisma.FabricConstructionScalarWhereInput
  data: Prisma.XOR<Prisma.FabricConstructionUpdateManyMutationInput, Prisma.FabricConstructionUncheckedUpdateManyWithoutFabricSpecInput>
}

export type FabricConstructionScalarWhereInput = {
  AND?: Prisma.FabricConstructionScalarWhereInput | Prisma.FabricConstructionScalarWhereInput[]
  OR?: Prisma.FabricConstructionScalarWhereInput[]
  NOT?: Prisma.FabricConstructionScalarWhereInput | Prisma.FabricConstructionScalarWhereInput[]
  id?: Prisma.StringFilter<"FabricConstruction"> | string
  fabricSpecId?: Prisma.StringFilter<"FabricConstruction"> | string
  rollCount?: Prisma.IntFilter<"FabricConstruction"> | number
  warpingMachine?: Prisma.EnumWbMachineTypeFilter<"FabricConstruction"> | $Enums.WbMachineType
  coneCount?: Prisma.IntFilter<"FabricConstruction"> | number
  sectionCount?: Prisma.IntFilter<"FabricConstruction"> | number
  sectionLength?: Prisma.IntFilter<"FabricConstruction"> | number
  beamWidth?: Prisma.DecimalFilter<"FabricConstruction"> | runtime.Decimal | runtime.DecimalJsLike | number | string
  spareEnds?: Prisma.IntFilter<"FabricConstruction"> | number
  beamingLoss?: Prisma.IntNullableFilter<"FabricConstruction"> | number | null
  createdAt?: Prisma.DateTimeFilter<"FabricConstruction"> | Date | string
  updatedAt?: Prisma.DateTimeNullableFilter<"FabricConstruction"> | Date | string | null
}

export type FabricConstructionCreateManyFabricSpecInput = {
  id?: string
  rollCount: number
  warpingMachine: $Enums.WbMachineType
  coneCount: number
  sectionCount: number
  sectionLength: number
  beamWidth: runtime.Decimal | runtime.DecimalJsLike | number | string
  spareEnds: number
  beamingLoss?: number | null
  createdAt?: Date | string
  updatedAt?: Date | string | null
}

export type FabricConstructionUpdateWithoutFabricSpecInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  rollCount?: Prisma.IntFieldUpdateOperationsInput | number
  warpingMachine?: Prisma.EnumWbMachineTypeFieldUpdateOperationsInput | $Enums.WbMachineType
  coneCount?: Prisma.IntFieldUpdateOperationsInput | number
  sectionCount?: Prisma.IntFieldUpdateOperationsInput | number
  sectionLength?: Prisma.IntFieldUpdateOperationsInput | number
  beamWidth?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  spareEnds?: Prisma.IntFieldUpdateOperationsInput | number
  beamingLoss?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
}

export type FabricConstructionUncheckedUpdateWithoutFabricSpecInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  rollCount?: Prisma.IntFieldUpdateOperationsInput | number
  warpingMachine?: Prisma.EnumWbMachineTypeFieldUpdateOperationsInput | $Enums.WbMachineType
  coneCount?: Prisma.IntFieldUpdateOperationsInput | number
  sectionCount?: Prisma.IntFieldUpdateOperationsInput | number
  sectionLength?: Prisma.IntFieldUpdateOperationsInput | number
  beamWidth?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  spareEnds?: Prisma.IntFieldUpdateOperationsInput | number
  beamingLoss?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
}

export type FabricConstructionUncheckedUpdateManyWithoutFabricSpecInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  rollCount?: Prisma.IntFieldUpdateOperationsInput | number
  warpingMachine?: Prisma.EnumWbMachineTypeFieldUpdateOperationsInput | $Enums.WbMachineType
  coneCount?: Prisma.IntFieldUpdateOperationsInput | number
  sectionCount?: Prisma.IntFieldUpdateOperationsInput | number
  sectionLength?: Prisma.IntFieldUpdateOperationsInput | number
  beamWidth?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  spareEnds?: Prisma.IntFieldUpdateOperationsInput | number
  beamingLoss?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
}



export type FabricConstructionSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  fabricSpecId?: boolean
  rollCount?: boolean
  warpingMachine?: boolean
  coneCount?: boolean
  sectionCount?: boolean
  sectionLength?: boolean
  beamWidth?: boolean
  spareEnds?: boolean
  beamingLoss?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  fabricSpec?: boolean | Prisma.FabricSpecDefaultArgs<ExtArgs>
}, ExtArgs["result"]["fabricConstruction"]>

export type FabricConstructionSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  fabricSpecId?: boolean
  rollCount?: boolean
  warpingMachine?: boolean
  coneCount?: boolean
  sectionCount?: boolean
  sectionLength?: boolean
  beamWidth?: boolean
  spareEnds?: boolean
  beamingLoss?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  fabricSpec?: boolean | Prisma.FabricSpecDefaultArgs<ExtArgs>
}, ExtArgs["result"]["fabricConstruction"]>

export type FabricConstructionSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  fabricSpecId?: boolean
  rollCount?: boolean
  warpingMachine?: boolean
  coneCount?: boolean
  sectionCount?: boolean
  sectionLength?: boolean
  beamWidth?: boolean
  spareEnds?: boolean
  beamingLoss?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  fabricSpec?: boolean | Prisma.FabricSpecDefaultArgs<ExtArgs>
}, ExtArgs["result"]["fabricConstruction"]>

export type FabricConstructionSelectScalar = {
  id?: boolean
  fabricSpecId?: boolean
  rollCount?: boolean
  warpingMachine?: boolean
  coneCount?: boolean
  sectionCount?: boolean
  sectionLength?: boolean
  beamWidth?: boolean
  spareEnds?: boolean
  beamingLoss?: boolean
  createdAt?: boolean
  updatedAt?: boolean
}

export type FabricConstructionOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "fabricSpecId" | "rollCount" | "warpingMachine" | "coneCount" | "sectionCount" | "sectionLength" | "beamWidth" | "spareEnds" | "beamingLoss" | "createdAt" | "updatedAt", ExtArgs["result"]["fabricConstruction"]>
export type FabricConstructionInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  fabricSpec?: boolean | Prisma.FabricSpecDefaultArgs<ExtArgs>
}
export type FabricConstructionIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  fabricSpec?: boolean | Prisma.FabricSpecDefaultArgs<ExtArgs>
}
export type FabricConstructionIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  fabricSpec?: boolean | Prisma.FabricSpecDefaultArgs<ExtArgs>
}

export type $FabricConstructionPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "FabricConstruction"
  objects: {
    fabricSpec: Prisma.$FabricSpecPayload<ExtArgs>
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    fabricSpecId: string
    rollCount: number
    warpingMachine: $Enums.WbMachineType
    coneCount: number
    sectionCount: number
    sectionLength: number
    beamWidth: runtime.Decimal
    spareEnds: number
    beamingLoss: number | null
    createdAt: Date
    updatedAt: Date | null
  }, ExtArgs["result"]["fabricConstruction"]>
  composites: {}
}

export type FabricConstructionGetPayload<S extends boolean | null | undefined | FabricConstructionDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$FabricConstructionPayload, S>

export type FabricConstructionCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<FabricConstructionFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: FabricConstructionCountAggregateInputType | true
  }

export interface FabricConstructionDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['FabricConstruction'], meta: { name: 'FabricConstruction' } }
  /**
   * Find zero or one FabricConstruction that matches the filter.
   * @param {FabricConstructionFindUniqueArgs} args - Arguments to find a FabricConstruction
   * @example
   * // Get one FabricConstruction
   * const fabricConstruction = await prisma.fabricConstruction.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends FabricConstructionFindUniqueArgs>(args: Prisma.SelectSubset<T, FabricConstructionFindUniqueArgs<ExtArgs>>): Prisma.Prisma__FabricConstructionClient<runtime.Types.Result.GetResult<Prisma.$FabricConstructionPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one FabricConstruction that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {FabricConstructionFindUniqueOrThrowArgs} args - Arguments to find a FabricConstruction
   * @example
   * // Get one FabricConstruction
   * const fabricConstruction = await prisma.fabricConstruction.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends FabricConstructionFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, FabricConstructionFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__FabricConstructionClient<runtime.Types.Result.GetResult<Prisma.$FabricConstructionPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first FabricConstruction that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {FabricConstructionFindFirstArgs} args - Arguments to find a FabricConstruction
   * @example
   * // Get one FabricConstruction
   * const fabricConstruction = await prisma.fabricConstruction.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends FabricConstructionFindFirstArgs>(args?: Prisma.SelectSubset<T, FabricConstructionFindFirstArgs<ExtArgs>>): Prisma.Prisma__FabricConstructionClient<runtime.Types.Result.GetResult<Prisma.$FabricConstructionPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first FabricConstruction that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {FabricConstructionFindFirstOrThrowArgs} args - Arguments to find a FabricConstruction
   * @example
   * // Get one FabricConstruction
   * const fabricConstruction = await prisma.fabricConstruction.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends FabricConstructionFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, FabricConstructionFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__FabricConstructionClient<runtime.Types.Result.GetResult<Prisma.$FabricConstructionPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more FabricConstructions that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {FabricConstructionFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all FabricConstructions
   * const fabricConstructions = await prisma.fabricConstruction.findMany()
   * 
   * // Get first 10 FabricConstructions
   * const fabricConstructions = await prisma.fabricConstruction.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const fabricConstructionWithIdOnly = await prisma.fabricConstruction.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends FabricConstructionFindManyArgs>(args?: Prisma.SelectSubset<T, FabricConstructionFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$FabricConstructionPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a FabricConstruction.
   * @param {FabricConstructionCreateArgs} args - Arguments to create a FabricConstruction.
   * @example
   * // Create one FabricConstruction
   * const FabricConstruction = await prisma.fabricConstruction.create({
   *   data: {
   *     // ... data to create a FabricConstruction
   *   }
   * })
   * 
   */
  create<T extends FabricConstructionCreateArgs>(args: Prisma.SelectSubset<T, FabricConstructionCreateArgs<ExtArgs>>): Prisma.Prisma__FabricConstructionClient<runtime.Types.Result.GetResult<Prisma.$FabricConstructionPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many FabricConstructions.
   * @param {FabricConstructionCreateManyArgs} args - Arguments to create many FabricConstructions.
   * @example
   * // Create many FabricConstructions
   * const fabricConstruction = await prisma.fabricConstruction.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends FabricConstructionCreateManyArgs>(args?: Prisma.SelectSubset<T, FabricConstructionCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many FabricConstructions and returns the data saved in the database.
   * @param {FabricConstructionCreateManyAndReturnArgs} args - Arguments to create many FabricConstructions.
   * @example
   * // Create many FabricConstructions
   * const fabricConstruction = await prisma.fabricConstruction.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many FabricConstructions and only return the `id`
   * const fabricConstructionWithIdOnly = await prisma.fabricConstruction.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends FabricConstructionCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, FabricConstructionCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$FabricConstructionPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a FabricConstruction.
   * @param {FabricConstructionDeleteArgs} args - Arguments to delete one FabricConstruction.
   * @example
   * // Delete one FabricConstruction
   * const FabricConstruction = await prisma.fabricConstruction.delete({
   *   where: {
   *     // ... filter to delete one FabricConstruction
   *   }
   * })
   * 
   */
  delete<T extends FabricConstructionDeleteArgs>(args: Prisma.SelectSubset<T, FabricConstructionDeleteArgs<ExtArgs>>): Prisma.Prisma__FabricConstructionClient<runtime.Types.Result.GetResult<Prisma.$FabricConstructionPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one FabricConstruction.
   * @param {FabricConstructionUpdateArgs} args - Arguments to update one FabricConstruction.
   * @example
   * // Update one FabricConstruction
   * const fabricConstruction = await prisma.fabricConstruction.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends FabricConstructionUpdateArgs>(args: Prisma.SelectSubset<T, FabricConstructionUpdateArgs<ExtArgs>>): Prisma.Prisma__FabricConstructionClient<runtime.Types.Result.GetResult<Prisma.$FabricConstructionPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more FabricConstructions.
   * @param {FabricConstructionDeleteManyArgs} args - Arguments to filter FabricConstructions to delete.
   * @example
   * // Delete a few FabricConstructions
   * const { count } = await prisma.fabricConstruction.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends FabricConstructionDeleteManyArgs>(args?: Prisma.SelectSubset<T, FabricConstructionDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more FabricConstructions.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {FabricConstructionUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many FabricConstructions
   * const fabricConstruction = await prisma.fabricConstruction.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends FabricConstructionUpdateManyArgs>(args: Prisma.SelectSubset<T, FabricConstructionUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more FabricConstructions and returns the data updated in the database.
   * @param {FabricConstructionUpdateManyAndReturnArgs} args - Arguments to update many FabricConstructions.
   * @example
   * // Update many FabricConstructions
   * const fabricConstruction = await prisma.fabricConstruction.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more FabricConstructions and only return the `id`
   * const fabricConstructionWithIdOnly = await prisma.fabricConstruction.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends FabricConstructionUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, FabricConstructionUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$FabricConstructionPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one FabricConstruction.
   * @param {FabricConstructionUpsertArgs} args - Arguments to update or create a FabricConstruction.
   * @example
   * // Update or create a FabricConstruction
   * const fabricConstruction = await prisma.fabricConstruction.upsert({
   *   create: {
   *     // ... data to create a FabricConstruction
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the FabricConstruction we want to update
   *   }
   * })
   */
  upsert<T extends FabricConstructionUpsertArgs>(args: Prisma.SelectSubset<T, FabricConstructionUpsertArgs<ExtArgs>>): Prisma.Prisma__FabricConstructionClient<runtime.Types.Result.GetResult<Prisma.$FabricConstructionPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of FabricConstructions.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {FabricConstructionCountArgs} args - Arguments to filter FabricConstructions to count.
   * @example
   * // Count the number of FabricConstructions
   * const count = await prisma.fabricConstruction.count({
   *   where: {
   *     // ... the filter for the FabricConstructions we want to count
   *   }
   * })
  **/
  count<T extends FabricConstructionCountArgs>(
    args?: Prisma.Subset<T, FabricConstructionCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], FabricConstructionCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a FabricConstruction.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {FabricConstructionAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends FabricConstructionAggregateArgs>(args: Prisma.Subset<T, FabricConstructionAggregateArgs>): Prisma.PrismaPromise<GetFabricConstructionAggregateType<T>>

  /**
   * Group by FabricConstruction.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {FabricConstructionGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends FabricConstructionGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: FabricConstructionGroupByArgs['orderBy'] }
      : { orderBy?: FabricConstructionGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, FabricConstructionGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetFabricConstructionGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the FabricConstruction model
 */
readonly fields: FabricConstructionFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for FabricConstruction.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__FabricConstructionClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  fabricSpec<T extends Prisma.FabricSpecDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.FabricSpecDefaultArgs<ExtArgs>>): Prisma.Prisma__FabricSpecClient<runtime.Types.Result.GetResult<Prisma.$FabricSpecPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the FabricConstruction model
 */
export interface FabricConstructionFieldRefs {
  readonly id: Prisma.FieldRef<"FabricConstruction", 'String'>
  readonly fabricSpecId: Prisma.FieldRef<"FabricConstruction", 'String'>
  readonly rollCount: Prisma.FieldRef<"FabricConstruction", 'Int'>
  readonly warpingMachine: Prisma.FieldRef<"FabricConstruction", 'WbMachineType'>
  readonly coneCount: Prisma.FieldRef<"FabricConstruction", 'Int'>
  readonly sectionCount: Prisma.FieldRef<"FabricConstruction", 'Int'>
  readonly sectionLength: Prisma.FieldRef<"FabricConstruction", 'Int'>
  readonly beamWidth: Prisma.FieldRef<"FabricConstruction", 'Decimal'>
  readonly spareEnds: Prisma.FieldRef<"FabricConstruction", 'Int'>
  readonly beamingLoss: Prisma.FieldRef<"FabricConstruction", 'Int'>
  readonly createdAt: Prisma.FieldRef<"FabricConstruction", 'DateTime'>
  readonly updatedAt: Prisma.FieldRef<"FabricConstruction", 'DateTime'>
}
    

// Custom InputTypes
/**
 * FabricConstruction findUnique
 */
export type FabricConstructionFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the FabricConstruction
   */
  select?: Prisma.FabricConstructionSelect<ExtArgs> | null
  /**
   * Omit specific fields from the FabricConstruction
   */
  omit?: Prisma.FabricConstructionOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.FabricConstructionInclude<ExtArgs> | null
  /**
   * Filter, which FabricConstruction to fetch.
   */
  where: Prisma.FabricConstructionWhereUniqueInput
}

/**
 * FabricConstruction findUniqueOrThrow
 */
export type FabricConstructionFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the FabricConstruction
   */
  select?: Prisma.FabricConstructionSelect<ExtArgs> | null
  /**
   * Omit specific fields from the FabricConstruction
   */
  omit?: Prisma.FabricConstructionOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.FabricConstructionInclude<ExtArgs> | null
  /**
   * Filter, which FabricConstruction to fetch.
   */
  where: Prisma.FabricConstructionWhereUniqueInput
}

/**
 * FabricConstruction findFirst
 */
export type FabricConstructionFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the FabricConstruction
   */
  select?: Prisma.FabricConstructionSelect<ExtArgs> | null
  /**
   * Omit specific fields from the FabricConstruction
   */
  omit?: Prisma.FabricConstructionOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.FabricConstructionInclude<ExtArgs> | null
  /**
   * Filter, which FabricConstruction to fetch.
   */
  where?: Prisma.FabricConstructionWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of FabricConstructions to fetch.
   */
  orderBy?: Prisma.FabricConstructionOrderByWithRelationInput | Prisma.FabricConstructionOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for FabricConstructions.
   */
  cursor?: Prisma.FabricConstructionWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` FabricConstructions from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` FabricConstructions.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of FabricConstructions.
   */
  distinct?: Prisma.FabricConstructionScalarFieldEnum | Prisma.FabricConstructionScalarFieldEnum[]
}

/**
 * FabricConstruction findFirstOrThrow
 */
export type FabricConstructionFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the FabricConstruction
   */
  select?: Prisma.FabricConstructionSelect<ExtArgs> | null
  /**
   * Omit specific fields from the FabricConstruction
   */
  omit?: Prisma.FabricConstructionOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.FabricConstructionInclude<ExtArgs> | null
  /**
   * Filter, which FabricConstruction to fetch.
   */
  where?: Prisma.FabricConstructionWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of FabricConstructions to fetch.
   */
  orderBy?: Prisma.FabricConstructionOrderByWithRelationInput | Prisma.FabricConstructionOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for FabricConstructions.
   */
  cursor?: Prisma.FabricConstructionWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` FabricConstructions from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` FabricConstructions.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of FabricConstructions.
   */
  distinct?: Prisma.FabricConstructionScalarFieldEnum | Prisma.FabricConstructionScalarFieldEnum[]
}

/**
 * FabricConstruction findMany
 */
export type FabricConstructionFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the FabricConstruction
   */
  select?: Prisma.FabricConstructionSelect<ExtArgs> | null
  /**
   * Omit specific fields from the FabricConstruction
   */
  omit?: Prisma.FabricConstructionOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.FabricConstructionInclude<ExtArgs> | null
  /**
   * Filter, which FabricConstructions to fetch.
   */
  where?: Prisma.FabricConstructionWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of FabricConstructions to fetch.
   */
  orderBy?: Prisma.FabricConstructionOrderByWithRelationInput | Prisma.FabricConstructionOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing FabricConstructions.
   */
  cursor?: Prisma.FabricConstructionWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` FabricConstructions from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` FabricConstructions.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of FabricConstructions.
   */
  distinct?: Prisma.FabricConstructionScalarFieldEnum | Prisma.FabricConstructionScalarFieldEnum[]
}

/**
 * FabricConstruction create
 */
export type FabricConstructionCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the FabricConstruction
   */
  select?: Prisma.FabricConstructionSelect<ExtArgs> | null
  /**
   * Omit specific fields from the FabricConstruction
   */
  omit?: Prisma.FabricConstructionOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.FabricConstructionInclude<ExtArgs> | null
  /**
   * The data needed to create a FabricConstruction.
   */
  data: Prisma.XOR<Prisma.FabricConstructionCreateInput, Prisma.FabricConstructionUncheckedCreateInput>
}

/**
 * FabricConstruction createMany
 */
export type FabricConstructionCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many FabricConstructions.
   */
  data: Prisma.FabricConstructionCreateManyInput | Prisma.FabricConstructionCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * FabricConstruction createManyAndReturn
 */
export type FabricConstructionCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the FabricConstruction
   */
  select?: Prisma.FabricConstructionSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the FabricConstruction
   */
  omit?: Prisma.FabricConstructionOmit<ExtArgs> | null
  /**
   * The data used to create many FabricConstructions.
   */
  data: Prisma.FabricConstructionCreateManyInput | Prisma.FabricConstructionCreateManyInput[]
  skipDuplicates?: boolean
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.FabricConstructionIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * FabricConstruction update
 */
export type FabricConstructionUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the FabricConstruction
   */
  select?: Prisma.FabricConstructionSelect<ExtArgs> | null
  /**
   * Omit specific fields from the FabricConstruction
   */
  omit?: Prisma.FabricConstructionOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.FabricConstructionInclude<ExtArgs> | null
  /**
   * The data needed to update a FabricConstruction.
   */
  data: Prisma.XOR<Prisma.FabricConstructionUpdateInput, Prisma.FabricConstructionUncheckedUpdateInput>
  /**
   * Choose, which FabricConstruction to update.
   */
  where: Prisma.FabricConstructionWhereUniqueInput
}

/**
 * FabricConstruction updateMany
 */
export type FabricConstructionUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update FabricConstructions.
   */
  data: Prisma.XOR<Prisma.FabricConstructionUpdateManyMutationInput, Prisma.FabricConstructionUncheckedUpdateManyInput>
  /**
   * Filter which FabricConstructions to update
   */
  where?: Prisma.FabricConstructionWhereInput
  /**
   * Limit how many FabricConstructions to update.
   */
  limit?: number
}

/**
 * FabricConstruction updateManyAndReturn
 */
export type FabricConstructionUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the FabricConstruction
   */
  select?: Prisma.FabricConstructionSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the FabricConstruction
   */
  omit?: Prisma.FabricConstructionOmit<ExtArgs> | null
  /**
   * The data used to update FabricConstructions.
   */
  data: Prisma.XOR<Prisma.FabricConstructionUpdateManyMutationInput, Prisma.FabricConstructionUncheckedUpdateManyInput>
  /**
   * Filter which FabricConstructions to update
   */
  where?: Prisma.FabricConstructionWhereInput
  /**
   * Limit how many FabricConstructions to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.FabricConstructionIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * FabricConstruction upsert
 */
export type FabricConstructionUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the FabricConstruction
   */
  select?: Prisma.FabricConstructionSelect<ExtArgs> | null
  /**
   * Omit specific fields from the FabricConstruction
   */
  omit?: Prisma.FabricConstructionOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.FabricConstructionInclude<ExtArgs> | null
  /**
   * The filter to search for the FabricConstruction to update in case it exists.
   */
  where: Prisma.FabricConstructionWhereUniqueInput
  /**
   * In case the FabricConstruction found by the `where` argument doesn't exist, create a new FabricConstruction with this data.
   */
  create: Prisma.XOR<Prisma.FabricConstructionCreateInput, Prisma.FabricConstructionUncheckedCreateInput>
  /**
   * In case the FabricConstruction was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.FabricConstructionUpdateInput, Prisma.FabricConstructionUncheckedUpdateInput>
}

/**
 * FabricConstruction delete
 */
export type FabricConstructionDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the FabricConstruction
   */
  select?: Prisma.FabricConstructionSelect<ExtArgs> | null
  /**
   * Omit specific fields from the FabricConstruction
   */
  omit?: Prisma.FabricConstructionOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.FabricConstructionInclude<ExtArgs> | null
  /**
   * Filter which FabricConstruction to delete.
   */
  where: Prisma.FabricConstructionWhereUniqueInput
}

/**
 * FabricConstruction deleteMany
 */
export type FabricConstructionDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which FabricConstructions to delete
   */
  where?: Prisma.FabricConstructionWhereInput
  /**
   * Limit how many FabricConstructions to delete.
   */
  limit?: number
}

/**
 * FabricConstruction without action
 */
export type FabricConstructionDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the FabricConstruction
   */
  select?: Prisma.FabricConstructionSelect<ExtArgs> | null
  /**
   * Omit specific fields from the FabricConstruction
   */
  omit?: Prisma.FabricConstructionOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.FabricConstructionInclude<ExtArgs> | null
}
