
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `WeavingMachine` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums.ts"
import type * as Prisma from "../internal/prismaNamespace.ts"

/**
 * Model WeavingMachine
 * 
 */
export type WeavingMachineModel = runtime.Types.Result.DefaultSelection<Prisma.$WeavingMachinePayload>

export type AggregateWeavingMachine = {
  _count: WeavingMachineCountAggregateOutputType | null
  _avg: WeavingMachineAvgAggregateOutputType | null
  _sum: WeavingMachineSumAggregateOutputType | null
  _min: WeavingMachineMinAggregateOutputType | null
  _max: WeavingMachineMaxAggregateOutputType | null
}

export type WeavingMachineAvgAggregateOutputType = {
  width: number | null
}

export type WeavingMachineSumAggregateOutputType = {
  width: number | null
}

export type WeavingMachineMinAggregateOutputType = {
  id: string | null
  name: string | null
  slug: string | null
  width: number | null
  type: string | null
}

export type WeavingMachineMaxAggregateOutputType = {
  id: string | null
  name: string | null
  slug: string | null
  width: number | null
  type: string | null
}

export type WeavingMachineCountAggregateOutputType = {
  id: number
  name: number
  slug: number
  width: number
  type: number
  _all: number
}


export type WeavingMachineAvgAggregateInputType = {
  width?: true
}

export type WeavingMachineSumAggregateInputType = {
  width?: true
}

export type WeavingMachineMinAggregateInputType = {
  id?: true
  name?: true
  slug?: true
  width?: true
  type?: true
}

export type WeavingMachineMaxAggregateInputType = {
  id?: true
  name?: true
  slug?: true
  width?: true
  type?: true
}

export type WeavingMachineCountAggregateInputType = {
  id?: true
  name?: true
  slug?: true
  width?: true
  type?: true
  _all?: true
}

export type WeavingMachineAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which WeavingMachine to aggregate.
   */
  where?: Prisma.WeavingMachineWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of WeavingMachines to fetch.
   */
  orderBy?: Prisma.WeavingMachineOrderByWithRelationInput | Prisma.WeavingMachineOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.WeavingMachineWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` WeavingMachines from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` WeavingMachines.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned WeavingMachines
  **/
  _count?: true | WeavingMachineCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to average
  **/
  _avg?: WeavingMachineAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to sum
  **/
  _sum?: WeavingMachineSumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: WeavingMachineMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: WeavingMachineMaxAggregateInputType
}

export type GetWeavingMachineAggregateType<T extends WeavingMachineAggregateArgs> = {
      [P in keyof T & keyof AggregateWeavingMachine]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateWeavingMachine[P]>
    : Prisma.GetScalarType<T[P], AggregateWeavingMachine[P]>
}




export type WeavingMachineGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.WeavingMachineWhereInput
  orderBy?: Prisma.WeavingMachineOrderByWithAggregationInput | Prisma.WeavingMachineOrderByWithAggregationInput[]
  by: Prisma.WeavingMachineScalarFieldEnum[] | Prisma.WeavingMachineScalarFieldEnum
  having?: Prisma.WeavingMachineScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: WeavingMachineCountAggregateInputType | true
  _avg?: WeavingMachineAvgAggregateInputType
  _sum?: WeavingMachineSumAggregateInputType
  _min?: WeavingMachineMinAggregateInputType
  _max?: WeavingMachineMaxAggregateInputType
}

export type WeavingMachineGroupByOutputType = {
  id: string
  name: string
  slug: string
  width: number
  type: string
  _count: WeavingMachineCountAggregateOutputType | null
  _avg: WeavingMachineAvgAggregateOutputType | null
  _sum: WeavingMachineSumAggregateOutputType | null
  _min: WeavingMachineMinAggregateOutputType | null
  _max: WeavingMachineMaxAggregateOutputType | null
}

type GetWeavingMachineGroupByPayload<T extends WeavingMachineGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<WeavingMachineGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof WeavingMachineGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], WeavingMachineGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], WeavingMachineGroupByOutputType[P]>
      }
    >
  >



export type WeavingMachineWhereInput = {
  AND?: Prisma.WeavingMachineWhereInput | Prisma.WeavingMachineWhereInput[]
  OR?: Prisma.WeavingMachineWhereInput[]
  NOT?: Prisma.WeavingMachineWhereInput | Prisma.WeavingMachineWhereInput[]
  id?: Prisma.StringFilter<"WeavingMachine"> | string
  name?: Prisma.StringFilter<"WeavingMachine"> | string
  slug?: Prisma.StringFilter<"WeavingMachine"> | string
  width?: Prisma.IntFilter<"WeavingMachine"> | number
  type?: Prisma.StringFilter<"WeavingMachine"> | string
}

export type WeavingMachineOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  name?: Prisma.SortOrder
  slug?: Prisma.SortOrder
  width?: Prisma.SortOrder
  type?: Prisma.SortOrder
}

export type WeavingMachineWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  name?: string
  slug?: string
  AND?: Prisma.WeavingMachineWhereInput | Prisma.WeavingMachineWhereInput[]
  OR?: Prisma.WeavingMachineWhereInput[]
  NOT?: Prisma.WeavingMachineWhereInput | Prisma.WeavingMachineWhereInput[]
  width?: Prisma.IntFilter<"WeavingMachine"> | number
  type?: Prisma.StringFilter<"WeavingMachine"> | string
}, "id" | "name" | "slug">

export type WeavingMachineOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  name?: Prisma.SortOrder
  slug?: Prisma.SortOrder
  width?: Prisma.SortOrder
  type?: Prisma.SortOrder
  _count?: Prisma.WeavingMachineCountOrderByAggregateInput
  _avg?: Prisma.WeavingMachineAvgOrderByAggregateInput
  _max?: Prisma.WeavingMachineMaxOrderByAggregateInput
  _min?: Prisma.WeavingMachineMinOrderByAggregateInput
  _sum?: Prisma.WeavingMachineSumOrderByAggregateInput
}

export type WeavingMachineScalarWhereWithAggregatesInput = {
  AND?: Prisma.WeavingMachineScalarWhereWithAggregatesInput | Prisma.WeavingMachineScalarWhereWithAggregatesInput[]
  OR?: Prisma.WeavingMachineScalarWhereWithAggregatesInput[]
  NOT?: Prisma.WeavingMachineScalarWhereWithAggregatesInput | Prisma.WeavingMachineScalarWhereWithAggregatesInput[]
  id?: Prisma.StringWithAggregatesFilter<"WeavingMachine"> | string
  name?: Prisma.StringWithAggregatesFilter<"WeavingMachine"> | string
  slug?: Prisma.StringWithAggregatesFilter<"WeavingMachine"> | string
  width?: Prisma.IntWithAggregatesFilter<"WeavingMachine"> | number
  type?: Prisma.StringWithAggregatesFilter<"WeavingMachine"> | string
}

export type WeavingMachineCreateInput = {
  id?: string
  name: string
  slug: string
  width: number
  type: string
}

export type WeavingMachineUncheckedCreateInput = {
  id?: string
  name: string
  slug: string
  width: number
  type: string
}

export type WeavingMachineUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  slug?: Prisma.StringFieldUpdateOperationsInput | string
  width?: Prisma.IntFieldUpdateOperationsInput | number
  type?: Prisma.StringFieldUpdateOperationsInput | string
}

export type WeavingMachineUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  slug?: Prisma.StringFieldUpdateOperationsInput | string
  width?: Prisma.IntFieldUpdateOperationsInput | number
  type?: Prisma.StringFieldUpdateOperationsInput | string
}

export type WeavingMachineCreateManyInput = {
  id?: string
  name: string
  slug: string
  width: number
  type: string
}

export type WeavingMachineUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  slug?: Prisma.StringFieldUpdateOperationsInput | string
  width?: Prisma.IntFieldUpdateOperationsInput | number
  type?: Prisma.StringFieldUpdateOperationsInput | string
}

export type WeavingMachineUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  slug?: Prisma.StringFieldUpdateOperationsInput | string
  width?: Prisma.IntFieldUpdateOperationsInput | number
  type?: Prisma.StringFieldUpdateOperationsInput | string
}

export type WeavingMachineCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  name?: Prisma.SortOrder
  slug?: Prisma.SortOrder
  width?: Prisma.SortOrder
  type?: Prisma.SortOrder
}

export type WeavingMachineAvgOrderByAggregateInput = {
  width?: Prisma.SortOrder
}

export type WeavingMachineMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  name?: Prisma.SortOrder
  slug?: Prisma.SortOrder
  width?: Prisma.SortOrder
  type?: Prisma.SortOrder
}

export type WeavingMachineMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  name?: Prisma.SortOrder
  slug?: Prisma.SortOrder
  width?: Prisma.SortOrder
  type?: Prisma.SortOrder
}

export type WeavingMachineSumOrderByAggregateInput = {
  width?: Prisma.SortOrder
}

export type IntFieldUpdateOperationsInput = {
  set?: number
  increment?: number
  decrement?: number
  multiply?: number
  divide?: number
}



export type WeavingMachineSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  name?: boolean
  slug?: boolean
  width?: boolean
  type?: boolean
}, ExtArgs["result"]["weavingMachine"]>

export type WeavingMachineSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  name?: boolean
  slug?: boolean
  width?: boolean
  type?: boolean
}, ExtArgs["result"]["weavingMachine"]>

export type WeavingMachineSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  name?: boolean
  slug?: boolean
  width?: boolean
  type?: boolean
}, ExtArgs["result"]["weavingMachine"]>

export type WeavingMachineSelectScalar = {
  id?: boolean
  name?: boolean
  slug?: boolean
  width?: boolean
  type?: boolean
}

export type WeavingMachineOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "name" | "slug" | "width" | "type", ExtArgs["result"]["weavingMachine"]>

export type $WeavingMachinePayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "WeavingMachine"
  objects: {}
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    name: string
    slug: string
    width: number
    type: string
  }, ExtArgs["result"]["weavingMachine"]>
  composites: {}
}

export type WeavingMachineGetPayload<S extends boolean | null | undefined | WeavingMachineDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$WeavingMachinePayload, S>

export type WeavingMachineCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<WeavingMachineFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: WeavingMachineCountAggregateInputType | true
  }

export interface WeavingMachineDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['WeavingMachine'], meta: { name: 'WeavingMachine' } }
  /**
   * Find zero or one WeavingMachine that matches the filter.
   * @param {WeavingMachineFindUniqueArgs} args - Arguments to find a WeavingMachine
   * @example
   * // Get one WeavingMachine
   * const weavingMachine = await prisma.weavingMachine.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends WeavingMachineFindUniqueArgs>(args: Prisma.SelectSubset<T, WeavingMachineFindUniqueArgs<ExtArgs>>): Prisma.Prisma__WeavingMachineClient<runtime.Types.Result.GetResult<Prisma.$WeavingMachinePayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one WeavingMachine that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {WeavingMachineFindUniqueOrThrowArgs} args - Arguments to find a WeavingMachine
   * @example
   * // Get one WeavingMachine
   * const weavingMachine = await prisma.weavingMachine.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends WeavingMachineFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, WeavingMachineFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__WeavingMachineClient<runtime.Types.Result.GetResult<Prisma.$WeavingMachinePayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first WeavingMachine that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {WeavingMachineFindFirstArgs} args - Arguments to find a WeavingMachine
   * @example
   * // Get one WeavingMachine
   * const weavingMachine = await prisma.weavingMachine.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends WeavingMachineFindFirstArgs>(args?: Prisma.SelectSubset<T, WeavingMachineFindFirstArgs<ExtArgs>>): Prisma.Prisma__WeavingMachineClient<runtime.Types.Result.GetResult<Prisma.$WeavingMachinePayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first WeavingMachine that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {WeavingMachineFindFirstOrThrowArgs} args - Arguments to find a WeavingMachine
   * @example
   * // Get one WeavingMachine
   * const weavingMachine = await prisma.weavingMachine.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends WeavingMachineFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, WeavingMachineFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__WeavingMachineClient<runtime.Types.Result.GetResult<Prisma.$WeavingMachinePayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more WeavingMachines that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {WeavingMachineFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all WeavingMachines
   * const weavingMachines = await prisma.weavingMachine.findMany()
   * 
   * // Get first 10 WeavingMachines
   * const weavingMachines = await prisma.weavingMachine.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const weavingMachineWithIdOnly = await prisma.weavingMachine.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends WeavingMachineFindManyArgs>(args?: Prisma.SelectSubset<T, WeavingMachineFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$WeavingMachinePayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a WeavingMachine.
   * @param {WeavingMachineCreateArgs} args - Arguments to create a WeavingMachine.
   * @example
   * // Create one WeavingMachine
   * const WeavingMachine = await prisma.weavingMachine.create({
   *   data: {
   *     // ... data to create a WeavingMachine
   *   }
   * })
   * 
   */
  create<T extends WeavingMachineCreateArgs>(args: Prisma.SelectSubset<T, WeavingMachineCreateArgs<ExtArgs>>): Prisma.Prisma__WeavingMachineClient<runtime.Types.Result.GetResult<Prisma.$WeavingMachinePayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many WeavingMachines.
   * @param {WeavingMachineCreateManyArgs} args - Arguments to create many WeavingMachines.
   * @example
   * // Create many WeavingMachines
   * const weavingMachine = await prisma.weavingMachine.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends WeavingMachineCreateManyArgs>(args?: Prisma.SelectSubset<T, WeavingMachineCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many WeavingMachines and returns the data saved in the database.
   * @param {WeavingMachineCreateManyAndReturnArgs} args - Arguments to create many WeavingMachines.
   * @example
   * // Create many WeavingMachines
   * const weavingMachine = await prisma.weavingMachine.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many WeavingMachines and only return the `id`
   * const weavingMachineWithIdOnly = await prisma.weavingMachine.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends WeavingMachineCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, WeavingMachineCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$WeavingMachinePayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a WeavingMachine.
   * @param {WeavingMachineDeleteArgs} args - Arguments to delete one WeavingMachine.
   * @example
   * // Delete one WeavingMachine
   * const WeavingMachine = await prisma.weavingMachine.delete({
   *   where: {
   *     // ... filter to delete one WeavingMachine
   *   }
   * })
   * 
   */
  delete<T extends WeavingMachineDeleteArgs>(args: Prisma.SelectSubset<T, WeavingMachineDeleteArgs<ExtArgs>>): Prisma.Prisma__WeavingMachineClient<runtime.Types.Result.GetResult<Prisma.$WeavingMachinePayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one WeavingMachine.
   * @param {WeavingMachineUpdateArgs} args - Arguments to update one WeavingMachine.
   * @example
   * // Update one WeavingMachine
   * const weavingMachine = await prisma.weavingMachine.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends WeavingMachineUpdateArgs>(args: Prisma.SelectSubset<T, WeavingMachineUpdateArgs<ExtArgs>>): Prisma.Prisma__WeavingMachineClient<runtime.Types.Result.GetResult<Prisma.$WeavingMachinePayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more WeavingMachines.
   * @param {WeavingMachineDeleteManyArgs} args - Arguments to filter WeavingMachines to delete.
   * @example
   * // Delete a few WeavingMachines
   * const { count } = await prisma.weavingMachine.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends WeavingMachineDeleteManyArgs>(args?: Prisma.SelectSubset<T, WeavingMachineDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more WeavingMachines.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {WeavingMachineUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many WeavingMachines
   * const weavingMachine = await prisma.weavingMachine.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends WeavingMachineUpdateManyArgs>(args: Prisma.SelectSubset<T, WeavingMachineUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more WeavingMachines and returns the data updated in the database.
   * @param {WeavingMachineUpdateManyAndReturnArgs} args - Arguments to update many WeavingMachines.
   * @example
   * // Update many WeavingMachines
   * const weavingMachine = await prisma.weavingMachine.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more WeavingMachines and only return the `id`
   * const weavingMachineWithIdOnly = await prisma.weavingMachine.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends WeavingMachineUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, WeavingMachineUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$WeavingMachinePayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one WeavingMachine.
   * @param {WeavingMachineUpsertArgs} args - Arguments to update or create a WeavingMachine.
   * @example
   * // Update or create a WeavingMachine
   * const weavingMachine = await prisma.weavingMachine.upsert({
   *   create: {
   *     // ... data to create a WeavingMachine
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the WeavingMachine we want to update
   *   }
   * })
   */
  upsert<T extends WeavingMachineUpsertArgs>(args: Prisma.SelectSubset<T, WeavingMachineUpsertArgs<ExtArgs>>): Prisma.Prisma__WeavingMachineClient<runtime.Types.Result.GetResult<Prisma.$WeavingMachinePayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of WeavingMachines.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {WeavingMachineCountArgs} args - Arguments to filter WeavingMachines to count.
   * @example
   * // Count the number of WeavingMachines
   * const count = await prisma.weavingMachine.count({
   *   where: {
   *     // ... the filter for the WeavingMachines we want to count
   *   }
   * })
  **/
  count<T extends WeavingMachineCountArgs>(
    args?: Prisma.Subset<T, WeavingMachineCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], WeavingMachineCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a WeavingMachine.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {WeavingMachineAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends WeavingMachineAggregateArgs>(args: Prisma.Subset<T, WeavingMachineAggregateArgs>): Prisma.PrismaPromise<GetWeavingMachineAggregateType<T>>

  /**
   * Group by WeavingMachine.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {WeavingMachineGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends WeavingMachineGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: WeavingMachineGroupByArgs['orderBy'] }
      : { orderBy?: WeavingMachineGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, WeavingMachineGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetWeavingMachineGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the WeavingMachine model
 */
readonly fields: WeavingMachineFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for WeavingMachine.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__WeavingMachineClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the WeavingMachine model
 */
export interface WeavingMachineFieldRefs {
  readonly id: Prisma.FieldRef<"WeavingMachine", 'String'>
  readonly name: Prisma.FieldRef<"WeavingMachine", 'String'>
  readonly slug: Prisma.FieldRef<"WeavingMachine", 'String'>
  readonly width: Prisma.FieldRef<"WeavingMachine", 'Int'>
  readonly type: Prisma.FieldRef<"WeavingMachine", 'String'>
}
    

// Custom InputTypes
/**
 * WeavingMachine findUnique
 */
export type WeavingMachineFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the WeavingMachine
   */
  select?: Prisma.WeavingMachineSelect<ExtArgs> | null
  /**
   * Omit specific fields from the WeavingMachine
   */
  omit?: Prisma.WeavingMachineOmit<ExtArgs> | null
  /**
   * Filter, which WeavingMachine to fetch.
   */
  where: Prisma.WeavingMachineWhereUniqueInput
}

/**
 * WeavingMachine findUniqueOrThrow
 */
export type WeavingMachineFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the WeavingMachine
   */
  select?: Prisma.WeavingMachineSelect<ExtArgs> | null
  /**
   * Omit specific fields from the WeavingMachine
   */
  omit?: Prisma.WeavingMachineOmit<ExtArgs> | null
  /**
   * Filter, which WeavingMachine to fetch.
   */
  where: Prisma.WeavingMachineWhereUniqueInput
}

/**
 * WeavingMachine findFirst
 */
export type WeavingMachineFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the WeavingMachine
   */
  select?: Prisma.WeavingMachineSelect<ExtArgs> | null
  /**
   * Omit specific fields from the WeavingMachine
   */
  omit?: Prisma.WeavingMachineOmit<ExtArgs> | null
  /**
   * Filter, which WeavingMachine to fetch.
   */
  where?: Prisma.WeavingMachineWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of WeavingMachines to fetch.
   */
  orderBy?: Prisma.WeavingMachineOrderByWithRelationInput | Prisma.WeavingMachineOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for WeavingMachines.
   */
  cursor?: Prisma.WeavingMachineWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` WeavingMachines from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` WeavingMachines.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of WeavingMachines.
   */
  distinct?: Prisma.WeavingMachineScalarFieldEnum | Prisma.WeavingMachineScalarFieldEnum[]
}

/**
 * WeavingMachine findFirstOrThrow
 */
export type WeavingMachineFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the WeavingMachine
   */
  select?: Prisma.WeavingMachineSelect<ExtArgs> | null
  /**
   * Omit specific fields from the WeavingMachine
   */
  omit?: Prisma.WeavingMachineOmit<ExtArgs> | null
  /**
   * Filter, which WeavingMachine to fetch.
   */
  where?: Prisma.WeavingMachineWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of WeavingMachines to fetch.
   */
  orderBy?: Prisma.WeavingMachineOrderByWithRelationInput | Prisma.WeavingMachineOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for WeavingMachines.
   */
  cursor?: Prisma.WeavingMachineWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` WeavingMachines from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` WeavingMachines.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of WeavingMachines.
   */
  distinct?: Prisma.WeavingMachineScalarFieldEnum | Prisma.WeavingMachineScalarFieldEnum[]
}

/**
 * WeavingMachine findMany
 */
export type WeavingMachineFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the WeavingMachine
   */
  select?: Prisma.WeavingMachineSelect<ExtArgs> | null
  /**
   * Omit specific fields from the WeavingMachine
   */
  omit?: Prisma.WeavingMachineOmit<ExtArgs> | null
  /**
   * Filter, which WeavingMachines to fetch.
   */
  where?: Prisma.WeavingMachineWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of WeavingMachines to fetch.
   */
  orderBy?: Prisma.WeavingMachineOrderByWithRelationInput | Prisma.WeavingMachineOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing WeavingMachines.
   */
  cursor?: Prisma.WeavingMachineWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` WeavingMachines from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` WeavingMachines.
   */
  skip?: number
  distinct?: Prisma.WeavingMachineScalarFieldEnum | Prisma.WeavingMachineScalarFieldEnum[]
}

/**
 * WeavingMachine create
 */
export type WeavingMachineCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the WeavingMachine
   */
  select?: Prisma.WeavingMachineSelect<ExtArgs> | null
  /**
   * Omit specific fields from the WeavingMachine
   */
  omit?: Prisma.WeavingMachineOmit<ExtArgs> | null
  /**
   * The data needed to create a WeavingMachine.
   */
  data: Prisma.XOR<Prisma.WeavingMachineCreateInput, Prisma.WeavingMachineUncheckedCreateInput>
}

/**
 * WeavingMachine createMany
 */
export type WeavingMachineCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many WeavingMachines.
   */
  data: Prisma.WeavingMachineCreateManyInput | Prisma.WeavingMachineCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * WeavingMachine createManyAndReturn
 */
export type WeavingMachineCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the WeavingMachine
   */
  select?: Prisma.WeavingMachineSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the WeavingMachine
   */
  omit?: Prisma.WeavingMachineOmit<ExtArgs> | null
  /**
   * The data used to create many WeavingMachines.
   */
  data: Prisma.WeavingMachineCreateManyInput | Prisma.WeavingMachineCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * WeavingMachine update
 */
export type WeavingMachineUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the WeavingMachine
   */
  select?: Prisma.WeavingMachineSelect<ExtArgs> | null
  /**
   * Omit specific fields from the WeavingMachine
   */
  omit?: Prisma.WeavingMachineOmit<ExtArgs> | null
  /**
   * The data needed to update a WeavingMachine.
   */
  data: Prisma.XOR<Prisma.WeavingMachineUpdateInput, Prisma.WeavingMachineUncheckedUpdateInput>
  /**
   * Choose, which WeavingMachine to update.
   */
  where: Prisma.WeavingMachineWhereUniqueInput
}

/**
 * WeavingMachine updateMany
 */
export type WeavingMachineUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update WeavingMachines.
   */
  data: Prisma.XOR<Prisma.WeavingMachineUpdateManyMutationInput, Prisma.WeavingMachineUncheckedUpdateManyInput>
  /**
   * Filter which WeavingMachines to update
   */
  where?: Prisma.WeavingMachineWhereInput
  /**
   * Limit how many WeavingMachines to update.
   */
  limit?: number
}

/**
 * WeavingMachine updateManyAndReturn
 */
export type WeavingMachineUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the WeavingMachine
   */
  select?: Prisma.WeavingMachineSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the WeavingMachine
   */
  omit?: Prisma.WeavingMachineOmit<ExtArgs> | null
  /**
   * The data used to update WeavingMachines.
   */
  data: Prisma.XOR<Prisma.WeavingMachineUpdateManyMutationInput, Prisma.WeavingMachineUncheckedUpdateManyInput>
  /**
   * Filter which WeavingMachines to update
   */
  where?: Prisma.WeavingMachineWhereInput
  /**
   * Limit how many WeavingMachines to update.
   */
  limit?: number
}

/**
 * WeavingMachine upsert
 */
export type WeavingMachineUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the WeavingMachine
   */
  select?: Prisma.WeavingMachineSelect<ExtArgs> | null
  /**
   * Omit specific fields from the WeavingMachine
   */
  omit?: Prisma.WeavingMachineOmit<ExtArgs> | null
  /**
   * The filter to search for the WeavingMachine to update in case it exists.
   */
  where: Prisma.WeavingMachineWhereUniqueInput
  /**
   * In case the WeavingMachine found by the `where` argument doesn't exist, create a new WeavingMachine with this data.
   */
  create: Prisma.XOR<Prisma.WeavingMachineCreateInput, Prisma.WeavingMachineUncheckedCreateInput>
  /**
   * In case the WeavingMachine was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.WeavingMachineUpdateInput, Prisma.WeavingMachineUncheckedUpdateInput>
}

/**
 * WeavingMachine delete
 */
export type WeavingMachineDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the WeavingMachine
   */
  select?: Prisma.WeavingMachineSelect<ExtArgs> | null
  /**
   * Omit specific fields from the WeavingMachine
   */
  omit?: Prisma.WeavingMachineOmit<ExtArgs> | null
  /**
   * Filter which WeavingMachine to delete.
   */
  where: Prisma.WeavingMachineWhereUniqueInput
}

/**
 * WeavingMachine deleteMany
 */
export type WeavingMachineDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which WeavingMachines to delete
   */
  where?: Prisma.WeavingMachineWhereInput
  /**
   * Limit how many WeavingMachines to delete.
   */
  limit?: number
}

/**
 * WeavingMachine without action
 */
export type WeavingMachineDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the WeavingMachine
   */
  select?: Prisma.WeavingMachineSelect<ExtArgs> | null
  /**
   * Omit specific fields from the WeavingMachine
   */
  omit?: Prisma.WeavingMachineOmit<ExtArgs> | null
}
