
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `Yarn` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums.ts"
import type * as Prisma from "../internal/prismaNamespace.ts"

/**
 * Model Yarn
 * 
 */
export type YarnModel = runtime.Types.Result.DefaultSelection<Prisma.$YarnPayload>

export type AggregateYarn = {
  _count: YarnCountAggregateOutputType | null
  _min: YarnMinAggregateOutputType | null
  _max: YarnMaxAggregateOutputType | null
}

export type YarnMinAggregateOutputType = {
  id: string | null
  name: string | null
  slug: string | null
  createdAt: Date | null
  updatedAt: Date | null
}

export type YarnMaxAggregateOutputType = {
  id: string | null
  name: string | null
  slug: string | null
  createdAt: Date | null
  updatedAt: Date | null
}

export type YarnCountAggregateOutputType = {
  id: number
  name: number
  slug: number
  createdAt: number
  updatedAt: number
  _all: number
}


export type YarnMinAggregateInputType = {
  id?: true
  name?: true
  slug?: true
  createdAt?: true
  updatedAt?: true
}

export type YarnMaxAggregateInputType = {
  id?: true
  name?: true
  slug?: true
  createdAt?: true
  updatedAt?: true
}

export type YarnCountAggregateInputType = {
  id?: true
  name?: true
  slug?: true
  createdAt?: true
  updatedAt?: true
  _all?: true
}

export type YarnAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which Yarn to aggregate.
   */
  where?: Prisma.YarnWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Yarns to fetch.
   */
  orderBy?: Prisma.YarnOrderByWithRelationInput | Prisma.YarnOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.YarnWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Yarns from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Yarns.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned Yarns
  **/
  _count?: true | YarnCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: YarnMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: YarnMaxAggregateInputType
}

export type GetYarnAggregateType<T extends YarnAggregateArgs> = {
      [P in keyof T & keyof AggregateYarn]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateYarn[P]>
    : Prisma.GetScalarType<T[P], AggregateYarn[P]>
}




export type YarnGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.YarnWhereInput
  orderBy?: Prisma.YarnOrderByWithAggregationInput | Prisma.YarnOrderByWithAggregationInput[]
  by: Prisma.YarnScalarFieldEnum[] | Prisma.YarnScalarFieldEnum
  having?: Prisma.YarnScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: YarnCountAggregateInputType | true
  _min?: YarnMinAggregateInputType
  _max?: YarnMaxAggregateInputType
}

export type YarnGroupByOutputType = {
  id: string
  name: string
  slug: string
  createdAt: Date
  updatedAt: Date | null
  _count: YarnCountAggregateOutputType | null
  _min: YarnMinAggregateOutputType | null
  _max: YarnMaxAggregateOutputType | null
}

export type GetYarnGroupByPayload<T extends YarnGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<YarnGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof YarnGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], YarnGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], YarnGroupByOutputType[P]>
      }
    >
  >



export type YarnWhereInput = {
  AND?: Prisma.YarnWhereInput | Prisma.YarnWhereInput[]
  OR?: Prisma.YarnWhereInput[]
  NOT?: Prisma.YarnWhereInput | Prisma.YarnWhereInput[]
  id?: Prisma.StringFilter<"Yarn"> | string
  name?: Prisma.StringFilter<"Yarn"> | string
  slug?: Prisma.StringFilter<"Yarn"> | string
  createdAt?: Prisma.DateTimeFilter<"Yarn"> | Date | string
  updatedAt?: Prisma.DateTimeNullableFilter<"Yarn"> | Date | string | null
  warpFabricSpecs?: Prisma.FabricSpecListRelationFilter
  weftFabricSpecs?: Prisma.FabricSpecListRelationFilter
}

export type YarnOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  name?: Prisma.SortOrder
  slug?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrderInput | Prisma.SortOrder
  warpFabricSpecs?: Prisma.FabricSpecOrderByRelationAggregateInput
  weftFabricSpecs?: Prisma.FabricSpecOrderByRelationAggregateInput
}

export type YarnWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  name?: string
  slug?: string
  AND?: Prisma.YarnWhereInput | Prisma.YarnWhereInput[]
  OR?: Prisma.YarnWhereInput[]
  NOT?: Prisma.YarnWhereInput | Prisma.YarnWhereInput[]
  createdAt?: Prisma.DateTimeFilter<"Yarn"> | Date | string
  updatedAt?: Prisma.DateTimeNullableFilter<"Yarn"> | Date | string | null
  warpFabricSpecs?: Prisma.FabricSpecListRelationFilter
  weftFabricSpecs?: Prisma.FabricSpecListRelationFilter
}, "id" | "name" | "slug">

export type YarnOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  name?: Prisma.SortOrder
  slug?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrderInput | Prisma.SortOrder
  _count?: Prisma.YarnCountOrderByAggregateInput
  _max?: Prisma.YarnMaxOrderByAggregateInput
  _min?: Prisma.YarnMinOrderByAggregateInput
}

export type YarnScalarWhereWithAggregatesInput = {
  AND?: Prisma.YarnScalarWhereWithAggregatesInput | Prisma.YarnScalarWhereWithAggregatesInput[]
  OR?: Prisma.YarnScalarWhereWithAggregatesInput[]
  NOT?: Prisma.YarnScalarWhereWithAggregatesInput | Prisma.YarnScalarWhereWithAggregatesInput[]
  id?: Prisma.StringWithAggregatesFilter<"Yarn"> | string
  name?: Prisma.StringWithAggregatesFilter<"Yarn"> | string
  slug?: Prisma.StringWithAggregatesFilter<"Yarn"> | string
  createdAt?: Prisma.DateTimeWithAggregatesFilter<"Yarn"> | Date | string
  updatedAt?: Prisma.DateTimeNullableWithAggregatesFilter<"Yarn"> | Date | string | null
}

export type YarnCreateInput = {
  id?: string
  name: string
  slug: string
  createdAt?: Date | string
  updatedAt?: Date | string | null
  warpFabricSpecs?: Prisma.FabricSpecCreateNestedManyWithoutWarpYarnInput
  weftFabricSpecs?: Prisma.FabricSpecCreateNestedManyWithoutWeftYarnInput
}

export type YarnUncheckedCreateInput = {
  id?: string
  name: string
  slug: string
  createdAt?: Date | string
  updatedAt?: Date | string | null
  warpFabricSpecs?: Prisma.FabricSpecUncheckedCreateNestedManyWithoutWarpYarnInput
  weftFabricSpecs?: Prisma.FabricSpecUncheckedCreateNestedManyWithoutWeftYarnInput
}

export type YarnUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  slug?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  warpFabricSpecs?: Prisma.FabricSpecUpdateManyWithoutWarpYarnNestedInput
  weftFabricSpecs?: Prisma.FabricSpecUpdateManyWithoutWeftYarnNestedInput
}

export type YarnUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  slug?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  warpFabricSpecs?: Prisma.FabricSpecUncheckedUpdateManyWithoutWarpYarnNestedInput
  weftFabricSpecs?: Prisma.FabricSpecUncheckedUpdateManyWithoutWeftYarnNestedInput
}

export type YarnCreateManyInput = {
  id?: string
  name: string
  slug: string
  createdAt?: Date | string
  updatedAt?: Date | string | null
}

export type YarnUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  slug?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
}

export type YarnUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  slug?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
}

export type YarnScalarRelationFilter = {
  is?: Prisma.YarnWhereInput
  isNot?: Prisma.YarnWhereInput
}

export type YarnCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  name?: Prisma.SortOrder
  slug?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type YarnMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  name?: Prisma.SortOrder
  slug?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type YarnMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  name?: Prisma.SortOrder
  slug?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type YarnCreateNestedOneWithoutWarpFabricSpecsInput = {
  create?: Prisma.XOR<Prisma.YarnCreateWithoutWarpFabricSpecsInput, Prisma.YarnUncheckedCreateWithoutWarpFabricSpecsInput>
  connectOrCreate?: Prisma.YarnCreateOrConnectWithoutWarpFabricSpecsInput
  connect?: Prisma.YarnWhereUniqueInput
}

export type YarnCreateNestedOneWithoutWeftFabricSpecsInput = {
  create?: Prisma.XOR<Prisma.YarnCreateWithoutWeftFabricSpecsInput, Prisma.YarnUncheckedCreateWithoutWeftFabricSpecsInput>
  connectOrCreate?: Prisma.YarnCreateOrConnectWithoutWeftFabricSpecsInput
  connect?: Prisma.YarnWhereUniqueInput
}

export type YarnUpdateOneRequiredWithoutWarpFabricSpecsNestedInput = {
  create?: Prisma.XOR<Prisma.YarnCreateWithoutWarpFabricSpecsInput, Prisma.YarnUncheckedCreateWithoutWarpFabricSpecsInput>
  connectOrCreate?: Prisma.YarnCreateOrConnectWithoutWarpFabricSpecsInput
  upsert?: Prisma.YarnUpsertWithoutWarpFabricSpecsInput
  connect?: Prisma.YarnWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.YarnUpdateToOneWithWhereWithoutWarpFabricSpecsInput, Prisma.YarnUpdateWithoutWarpFabricSpecsInput>, Prisma.YarnUncheckedUpdateWithoutWarpFabricSpecsInput>
}

export type YarnUpdateOneRequiredWithoutWeftFabricSpecsNestedInput = {
  create?: Prisma.XOR<Prisma.YarnCreateWithoutWeftFabricSpecsInput, Prisma.YarnUncheckedCreateWithoutWeftFabricSpecsInput>
  connectOrCreate?: Prisma.YarnCreateOrConnectWithoutWeftFabricSpecsInput
  upsert?: Prisma.YarnUpsertWithoutWeftFabricSpecsInput
  connect?: Prisma.YarnWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.YarnUpdateToOneWithWhereWithoutWeftFabricSpecsInput, Prisma.YarnUpdateWithoutWeftFabricSpecsInput>, Prisma.YarnUncheckedUpdateWithoutWeftFabricSpecsInput>
}

export type YarnCreateWithoutWarpFabricSpecsInput = {
  id?: string
  name: string
  slug: string
  createdAt?: Date | string
  updatedAt?: Date | string | null
  weftFabricSpecs?: Prisma.FabricSpecCreateNestedManyWithoutWeftYarnInput
}

export type YarnUncheckedCreateWithoutWarpFabricSpecsInput = {
  id?: string
  name: string
  slug: string
  createdAt?: Date | string
  updatedAt?: Date | string | null
  weftFabricSpecs?: Prisma.FabricSpecUncheckedCreateNestedManyWithoutWeftYarnInput
}

export type YarnCreateOrConnectWithoutWarpFabricSpecsInput = {
  where: Prisma.YarnWhereUniqueInput
  create: Prisma.XOR<Prisma.YarnCreateWithoutWarpFabricSpecsInput, Prisma.YarnUncheckedCreateWithoutWarpFabricSpecsInput>
}

export type YarnCreateWithoutWeftFabricSpecsInput = {
  id?: string
  name: string
  slug: string
  createdAt?: Date | string
  updatedAt?: Date | string | null
  warpFabricSpecs?: Prisma.FabricSpecCreateNestedManyWithoutWarpYarnInput
}

export type YarnUncheckedCreateWithoutWeftFabricSpecsInput = {
  id?: string
  name: string
  slug: string
  createdAt?: Date | string
  updatedAt?: Date | string | null
  warpFabricSpecs?: Prisma.FabricSpecUncheckedCreateNestedManyWithoutWarpYarnInput
}

export type YarnCreateOrConnectWithoutWeftFabricSpecsInput = {
  where: Prisma.YarnWhereUniqueInput
  create: Prisma.XOR<Prisma.YarnCreateWithoutWeftFabricSpecsInput, Prisma.YarnUncheckedCreateWithoutWeftFabricSpecsInput>
}

export type YarnUpsertWithoutWarpFabricSpecsInput = {
  update: Prisma.XOR<Prisma.YarnUpdateWithoutWarpFabricSpecsInput, Prisma.YarnUncheckedUpdateWithoutWarpFabricSpecsInput>
  create: Prisma.XOR<Prisma.YarnCreateWithoutWarpFabricSpecsInput, Prisma.YarnUncheckedCreateWithoutWarpFabricSpecsInput>
  where?: Prisma.YarnWhereInput
}

export type YarnUpdateToOneWithWhereWithoutWarpFabricSpecsInput = {
  where?: Prisma.YarnWhereInput
  data: Prisma.XOR<Prisma.YarnUpdateWithoutWarpFabricSpecsInput, Prisma.YarnUncheckedUpdateWithoutWarpFabricSpecsInput>
}

export type YarnUpdateWithoutWarpFabricSpecsInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  slug?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  weftFabricSpecs?: Prisma.FabricSpecUpdateManyWithoutWeftYarnNestedInput
}

export type YarnUncheckedUpdateWithoutWarpFabricSpecsInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  slug?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  weftFabricSpecs?: Prisma.FabricSpecUncheckedUpdateManyWithoutWeftYarnNestedInput
}

export type YarnUpsertWithoutWeftFabricSpecsInput = {
  update: Prisma.XOR<Prisma.YarnUpdateWithoutWeftFabricSpecsInput, Prisma.YarnUncheckedUpdateWithoutWeftFabricSpecsInput>
  create: Prisma.XOR<Prisma.YarnCreateWithoutWeftFabricSpecsInput, Prisma.YarnUncheckedCreateWithoutWeftFabricSpecsInput>
  where?: Prisma.YarnWhereInput
}

export type YarnUpdateToOneWithWhereWithoutWeftFabricSpecsInput = {
  where?: Prisma.YarnWhereInput
  data: Prisma.XOR<Prisma.YarnUpdateWithoutWeftFabricSpecsInput, Prisma.YarnUncheckedUpdateWithoutWeftFabricSpecsInput>
}

export type YarnUpdateWithoutWeftFabricSpecsInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  slug?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  warpFabricSpecs?: Prisma.FabricSpecUpdateManyWithoutWarpYarnNestedInput
}

export type YarnUncheckedUpdateWithoutWeftFabricSpecsInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  slug?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  warpFabricSpecs?: Prisma.FabricSpecUncheckedUpdateManyWithoutWarpYarnNestedInput
}


/**
 * Count Type YarnCountOutputType
 */

export type YarnCountOutputType = {
  warpFabricSpecs: number
  weftFabricSpecs: number
}

export type YarnCountOutputTypeSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  warpFabricSpecs?: boolean | YarnCountOutputTypeCountWarpFabricSpecsArgs
  weftFabricSpecs?: boolean | YarnCountOutputTypeCountWeftFabricSpecsArgs
}

/**
 * YarnCountOutputType without action
 */
export type YarnCountOutputTypeDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the YarnCountOutputType
   */
  select?: Prisma.YarnCountOutputTypeSelect<ExtArgs> | null
}

/**
 * YarnCountOutputType without action
 */
export type YarnCountOutputTypeCountWarpFabricSpecsArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.FabricSpecWhereInput
}

/**
 * YarnCountOutputType without action
 */
export type YarnCountOutputTypeCountWeftFabricSpecsArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.FabricSpecWhereInput
}


export type YarnSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  name?: boolean
  slug?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  warpFabricSpecs?: boolean | Prisma.Yarn$warpFabricSpecsArgs<ExtArgs>
  weftFabricSpecs?: boolean | Prisma.Yarn$weftFabricSpecsArgs<ExtArgs>
  _count?: boolean | Prisma.YarnCountOutputTypeDefaultArgs<ExtArgs>
}, ExtArgs["result"]["yarn"]>

export type YarnSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  name?: boolean
  slug?: boolean
  createdAt?: boolean
  updatedAt?: boolean
}, ExtArgs["result"]["yarn"]>

export type YarnSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  name?: boolean
  slug?: boolean
  createdAt?: boolean
  updatedAt?: boolean
}, ExtArgs["result"]["yarn"]>

export type YarnSelectScalar = {
  id?: boolean
  name?: boolean
  slug?: boolean
  createdAt?: boolean
  updatedAt?: boolean
}

export type YarnOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "name" | "slug" | "createdAt" | "updatedAt", ExtArgs["result"]["yarn"]>
export type YarnInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  warpFabricSpecs?: boolean | Prisma.Yarn$warpFabricSpecsArgs<ExtArgs>
  weftFabricSpecs?: boolean | Prisma.Yarn$weftFabricSpecsArgs<ExtArgs>
  _count?: boolean | Prisma.YarnCountOutputTypeDefaultArgs<ExtArgs>
}
export type YarnIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {}
export type YarnIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {}

export type $YarnPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "Yarn"
  objects: {
    warpFabricSpecs: Prisma.$FabricSpecPayload<ExtArgs>[]
    weftFabricSpecs: Prisma.$FabricSpecPayload<ExtArgs>[]
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    name: string
    slug: string
    createdAt: Date
    updatedAt: Date | null
  }, ExtArgs["result"]["yarn"]>
  composites: {}
}

export type YarnGetPayload<S extends boolean | null | undefined | YarnDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$YarnPayload, S>

export type YarnCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<YarnFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: YarnCountAggregateInputType | true
  }

export interface YarnDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['Yarn'], meta: { name: 'Yarn' } }
  /**
   * Find zero or one Yarn that matches the filter.
   * @param {YarnFindUniqueArgs} args - Arguments to find a Yarn
   * @example
   * // Get one Yarn
   * const yarn = await prisma.yarn.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends YarnFindUniqueArgs>(args: Prisma.SelectSubset<T, YarnFindUniqueArgs<ExtArgs>>): Prisma.Prisma__YarnClient<runtime.Types.Result.GetResult<Prisma.$YarnPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one Yarn that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {YarnFindUniqueOrThrowArgs} args - Arguments to find a Yarn
   * @example
   * // Get one Yarn
   * const yarn = await prisma.yarn.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends YarnFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, YarnFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__YarnClient<runtime.Types.Result.GetResult<Prisma.$YarnPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Yarn that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {YarnFindFirstArgs} args - Arguments to find a Yarn
   * @example
   * // Get one Yarn
   * const yarn = await prisma.yarn.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends YarnFindFirstArgs>(args?: Prisma.SelectSubset<T, YarnFindFirstArgs<ExtArgs>>): Prisma.Prisma__YarnClient<runtime.Types.Result.GetResult<Prisma.$YarnPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Yarn that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {YarnFindFirstOrThrowArgs} args - Arguments to find a Yarn
   * @example
   * // Get one Yarn
   * const yarn = await prisma.yarn.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends YarnFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, YarnFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__YarnClient<runtime.Types.Result.GetResult<Prisma.$YarnPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more Yarns that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {YarnFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all Yarns
   * const yarns = await prisma.yarn.findMany()
   * 
   * // Get first 10 Yarns
   * const yarns = await prisma.yarn.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const yarnWithIdOnly = await prisma.yarn.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends YarnFindManyArgs>(args?: Prisma.SelectSubset<T, YarnFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$YarnPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a Yarn.
   * @param {YarnCreateArgs} args - Arguments to create a Yarn.
   * @example
   * // Create one Yarn
   * const Yarn = await prisma.yarn.create({
   *   data: {
   *     // ... data to create a Yarn
   *   }
   * })
   * 
   */
  create<T extends YarnCreateArgs>(args: Prisma.SelectSubset<T, YarnCreateArgs<ExtArgs>>): Prisma.Prisma__YarnClient<runtime.Types.Result.GetResult<Prisma.$YarnPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many Yarns.
   * @param {YarnCreateManyArgs} args - Arguments to create many Yarns.
   * @example
   * // Create many Yarns
   * const yarn = await prisma.yarn.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends YarnCreateManyArgs>(args?: Prisma.SelectSubset<T, YarnCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many Yarns and returns the data saved in the database.
   * @param {YarnCreateManyAndReturnArgs} args - Arguments to create many Yarns.
   * @example
   * // Create many Yarns
   * const yarn = await prisma.yarn.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many Yarns and only return the `id`
   * const yarnWithIdOnly = await prisma.yarn.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends YarnCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, YarnCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$YarnPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a Yarn.
   * @param {YarnDeleteArgs} args - Arguments to delete one Yarn.
   * @example
   * // Delete one Yarn
   * const Yarn = await prisma.yarn.delete({
   *   where: {
   *     // ... filter to delete one Yarn
   *   }
   * })
   * 
   */
  delete<T extends YarnDeleteArgs>(args: Prisma.SelectSubset<T, YarnDeleteArgs<ExtArgs>>): Prisma.Prisma__YarnClient<runtime.Types.Result.GetResult<Prisma.$YarnPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one Yarn.
   * @param {YarnUpdateArgs} args - Arguments to update one Yarn.
   * @example
   * // Update one Yarn
   * const yarn = await prisma.yarn.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends YarnUpdateArgs>(args: Prisma.SelectSubset<T, YarnUpdateArgs<ExtArgs>>): Prisma.Prisma__YarnClient<runtime.Types.Result.GetResult<Prisma.$YarnPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more Yarns.
   * @param {YarnDeleteManyArgs} args - Arguments to filter Yarns to delete.
   * @example
   * // Delete a few Yarns
   * const { count } = await prisma.yarn.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends YarnDeleteManyArgs>(args?: Prisma.SelectSubset<T, YarnDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Yarns.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {YarnUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many Yarns
   * const yarn = await prisma.yarn.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends YarnUpdateManyArgs>(args: Prisma.SelectSubset<T, YarnUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Yarns and returns the data updated in the database.
   * @param {YarnUpdateManyAndReturnArgs} args - Arguments to update many Yarns.
   * @example
   * // Update many Yarns
   * const yarn = await prisma.yarn.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more Yarns and only return the `id`
   * const yarnWithIdOnly = await prisma.yarn.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends YarnUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, YarnUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$YarnPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one Yarn.
   * @param {YarnUpsertArgs} args - Arguments to update or create a Yarn.
   * @example
   * // Update or create a Yarn
   * const yarn = await prisma.yarn.upsert({
   *   create: {
   *     // ... data to create a Yarn
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the Yarn we want to update
   *   }
   * })
   */
  upsert<T extends YarnUpsertArgs>(args: Prisma.SelectSubset<T, YarnUpsertArgs<ExtArgs>>): Prisma.Prisma__YarnClient<runtime.Types.Result.GetResult<Prisma.$YarnPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of Yarns.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {YarnCountArgs} args - Arguments to filter Yarns to count.
   * @example
   * // Count the number of Yarns
   * const count = await prisma.yarn.count({
   *   where: {
   *     // ... the filter for the Yarns we want to count
   *   }
   * })
  **/
  count<T extends YarnCountArgs>(
    args?: Prisma.Subset<T, YarnCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], YarnCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a Yarn.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {YarnAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends YarnAggregateArgs>(args: Prisma.Subset<T, YarnAggregateArgs>): Prisma.PrismaPromise<GetYarnAggregateType<T>>

  /**
   * Group by Yarn.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {YarnGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends YarnGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: YarnGroupByArgs['orderBy'] }
      : { orderBy?: YarnGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, YarnGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetYarnGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the Yarn model
 */
readonly fields: YarnFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for Yarn.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__YarnClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  warpFabricSpecs<T extends Prisma.Yarn$warpFabricSpecsArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.Yarn$warpFabricSpecsArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$FabricSpecPayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  weftFabricSpecs<T extends Prisma.Yarn$weftFabricSpecsArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.Yarn$weftFabricSpecsArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$FabricSpecPayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the Yarn model
 */
export interface YarnFieldRefs {
  readonly id: Prisma.FieldRef<"Yarn", 'String'>
  readonly name: Prisma.FieldRef<"Yarn", 'String'>
  readonly slug: Prisma.FieldRef<"Yarn", 'String'>
  readonly createdAt: Prisma.FieldRef<"Yarn", 'DateTime'>
  readonly updatedAt: Prisma.FieldRef<"Yarn", 'DateTime'>
}
    

// Custom InputTypes
/**
 * Yarn findUnique
 */
export type YarnFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Yarn
   */
  select?: Prisma.YarnSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Yarn
   */
  omit?: Prisma.YarnOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.YarnInclude<ExtArgs> | null
  /**
   * Filter, which Yarn to fetch.
   */
  where: Prisma.YarnWhereUniqueInput
}

/**
 * Yarn findUniqueOrThrow
 */
export type YarnFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Yarn
   */
  select?: Prisma.YarnSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Yarn
   */
  omit?: Prisma.YarnOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.YarnInclude<ExtArgs> | null
  /**
   * Filter, which Yarn to fetch.
   */
  where: Prisma.YarnWhereUniqueInput
}

/**
 * Yarn findFirst
 */
export type YarnFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Yarn
   */
  select?: Prisma.YarnSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Yarn
   */
  omit?: Prisma.YarnOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.YarnInclude<ExtArgs> | null
  /**
   * Filter, which Yarn to fetch.
   */
  where?: Prisma.YarnWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Yarns to fetch.
   */
  orderBy?: Prisma.YarnOrderByWithRelationInput | Prisma.YarnOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for Yarns.
   */
  cursor?: Prisma.YarnWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Yarns from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Yarns.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Yarns.
   */
  distinct?: Prisma.YarnScalarFieldEnum | Prisma.YarnScalarFieldEnum[]
}

/**
 * Yarn findFirstOrThrow
 */
export type YarnFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Yarn
   */
  select?: Prisma.YarnSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Yarn
   */
  omit?: Prisma.YarnOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.YarnInclude<ExtArgs> | null
  /**
   * Filter, which Yarn to fetch.
   */
  where?: Prisma.YarnWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Yarns to fetch.
   */
  orderBy?: Prisma.YarnOrderByWithRelationInput | Prisma.YarnOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for Yarns.
   */
  cursor?: Prisma.YarnWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Yarns from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Yarns.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Yarns.
   */
  distinct?: Prisma.YarnScalarFieldEnum | Prisma.YarnScalarFieldEnum[]
}

/**
 * Yarn findMany
 */
export type YarnFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Yarn
   */
  select?: Prisma.YarnSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Yarn
   */
  omit?: Prisma.YarnOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.YarnInclude<ExtArgs> | null
  /**
   * Filter, which Yarns to fetch.
   */
  where?: Prisma.YarnWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Yarns to fetch.
   */
  orderBy?: Prisma.YarnOrderByWithRelationInput | Prisma.YarnOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing Yarns.
   */
  cursor?: Prisma.YarnWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Yarns from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Yarns.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Yarns.
   */
  distinct?: Prisma.YarnScalarFieldEnum | Prisma.YarnScalarFieldEnum[]
}

/**
 * Yarn create
 */
export type YarnCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Yarn
   */
  select?: Prisma.YarnSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Yarn
   */
  omit?: Prisma.YarnOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.YarnInclude<ExtArgs> | null
  /**
   * The data needed to create a Yarn.
   */
  data: Prisma.XOR<Prisma.YarnCreateInput, Prisma.YarnUncheckedCreateInput>
}

/**
 * Yarn createMany
 */
export type YarnCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many Yarns.
   */
  data: Prisma.YarnCreateManyInput | Prisma.YarnCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * Yarn createManyAndReturn
 */
export type YarnCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Yarn
   */
  select?: Prisma.YarnSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the Yarn
   */
  omit?: Prisma.YarnOmit<ExtArgs> | null
  /**
   * The data used to create many Yarns.
   */
  data: Prisma.YarnCreateManyInput | Prisma.YarnCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * Yarn update
 */
export type YarnUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Yarn
   */
  select?: Prisma.YarnSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Yarn
   */
  omit?: Prisma.YarnOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.YarnInclude<ExtArgs> | null
  /**
   * The data needed to update a Yarn.
   */
  data: Prisma.XOR<Prisma.YarnUpdateInput, Prisma.YarnUncheckedUpdateInput>
  /**
   * Choose, which Yarn to update.
   */
  where: Prisma.YarnWhereUniqueInput
}

/**
 * Yarn updateMany
 */
export type YarnUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update Yarns.
   */
  data: Prisma.XOR<Prisma.YarnUpdateManyMutationInput, Prisma.YarnUncheckedUpdateManyInput>
  /**
   * Filter which Yarns to update
   */
  where?: Prisma.YarnWhereInput
  /**
   * Limit how many Yarns to update.
   */
  limit?: number
}

/**
 * Yarn updateManyAndReturn
 */
export type YarnUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Yarn
   */
  select?: Prisma.YarnSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the Yarn
   */
  omit?: Prisma.YarnOmit<ExtArgs> | null
  /**
   * The data used to update Yarns.
   */
  data: Prisma.XOR<Prisma.YarnUpdateManyMutationInput, Prisma.YarnUncheckedUpdateManyInput>
  /**
   * Filter which Yarns to update
   */
  where?: Prisma.YarnWhereInput
  /**
   * Limit how many Yarns to update.
   */
  limit?: number
}

/**
 * Yarn upsert
 */
export type YarnUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Yarn
   */
  select?: Prisma.YarnSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Yarn
   */
  omit?: Prisma.YarnOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.YarnInclude<ExtArgs> | null
  /**
   * The filter to search for the Yarn to update in case it exists.
   */
  where: Prisma.YarnWhereUniqueInput
  /**
   * In case the Yarn found by the `where` argument doesn't exist, create a new Yarn with this data.
   */
  create: Prisma.XOR<Prisma.YarnCreateInput, Prisma.YarnUncheckedCreateInput>
  /**
   * In case the Yarn was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.YarnUpdateInput, Prisma.YarnUncheckedUpdateInput>
}

/**
 * Yarn delete
 */
export type YarnDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Yarn
   */
  select?: Prisma.YarnSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Yarn
   */
  omit?: Prisma.YarnOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.YarnInclude<ExtArgs> | null
  /**
   * Filter which Yarn to delete.
   */
  where: Prisma.YarnWhereUniqueInput
}

/**
 * Yarn deleteMany
 */
export type YarnDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which Yarns to delete
   */
  where?: Prisma.YarnWhereInput
  /**
   * Limit how many Yarns to delete.
   */
  limit?: number
}

/**
 * Yarn.warpFabricSpecs
 */
export type Yarn$warpFabricSpecsArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the FabricSpec
   */
  select?: Prisma.FabricSpecSelect<ExtArgs> | null
  /**
   * Omit specific fields from the FabricSpec
   */
  omit?: Prisma.FabricSpecOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.FabricSpecInclude<ExtArgs> | null
  where?: Prisma.FabricSpecWhereInput
  orderBy?: Prisma.FabricSpecOrderByWithRelationInput | Prisma.FabricSpecOrderByWithRelationInput[]
  cursor?: Prisma.FabricSpecWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.FabricSpecScalarFieldEnum | Prisma.FabricSpecScalarFieldEnum[]
}

/**
 * Yarn.weftFabricSpecs
 */
export type Yarn$weftFabricSpecsArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the FabricSpec
   */
  select?: Prisma.FabricSpecSelect<ExtArgs> | null
  /**
   * Omit specific fields from the FabricSpec
   */
  omit?: Prisma.FabricSpecOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.FabricSpecInclude<ExtArgs> | null
  where?: Prisma.FabricSpecWhereInput
  orderBy?: Prisma.FabricSpecOrderByWithRelationInput | Prisma.FabricSpecOrderByWithRelationInput[]
  cursor?: Prisma.FabricSpecWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.FabricSpecScalarFieldEnum | Prisma.FabricSpecScalarFieldEnum[]
}

/**
 * Yarn without action
 */
export type YarnDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Yarn
   */
  select?: Prisma.YarnSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Yarn
   */
  omit?: Prisma.YarnOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.YarnInclude<ExtArgs> | null
}
