
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `Yarns` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums.ts"
import type * as Prisma from "../internal/prismaNamespace.ts"

/**
 * Model Yarns
 * 
 */
export type YarnsModel = runtime.Types.Result.DefaultSelection<Prisma.$YarnsPayload>

export type AggregateYarns = {
  _count: YarnsCountAggregateOutputType | null
  _min: YarnsMinAggregateOutputType | null
  _max: YarnsMaxAggregateOutputType | null
}

export type YarnsMinAggregateOutputType = {
  id: string | null
  name: string | null
  slug: string | null
  createdAt: Date | null
  updatedAt: Date | null
}

export type YarnsMaxAggregateOutputType = {
  id: string | null
  name: string | null
  slug: string | null
  createdAt: Date | null
  updatedAt: Date | null
}

export type YarnsCountAggregateOutputType = {
  id: number
  name: number
  slug: number
  createdAt: number
  updatedAt: number
  _all: number
}


export type YarnsMinAggregateInputType = {
  id?: true
  name?: true
  slug?: true
  createdAt?: true
  updatedAt?: true
}

export type YarnsMaxAggregateInputType = {
  id?: true
  name?: true
  slug?: true
  createdAt?: true
  updatedAt?: true
}

export type YarnsCountAggregateInputType = {
  id?: true
  name?: true
  slug?: true
  createdAt?: true
  updatedAt?: true
  _all?: true
}

export type YarnsAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which Yarns to aggregate.
   */
  where?: Prisma.YarnsWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Yarns to fetch.
   */
  orderBy?: Prisma.YarnsOrderByWithRelationInput | Prisma.YarnsOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.YarnsWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Yarns from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Yarns.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned Yarns
  **/
  _count?: true | YarnsCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: YarnsMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: YarnsMaxAggregateInputType
}

export type GetYarnsAggregateType<T extends YarnsAggregateArgs> = {
      [P in keyof T & keyof AggregateYarns]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateYarns[P]>
    : Prisma.GetScalarType<T[P], AggregateYarns[P]>
}




export type YarnsGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.YarnsWhereInput
  orderBy?: Prisma.YarnsOrderByWithAggregationInput | Prisma.YarnsOrderByWithAggregationInput[]
  by: Prisma.YarnsScalarFieldEnum[] | Prisma.YarnsScalarFieldEnum
  having?: Prisma.YarnsScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: YarnsCountAggregateInputType | true
  _min?: YarnsMinAggregateInputType
  _max?: YarnsMaxAggregateInputType
}

export type YarnsGroupByOutputType = {
  id: string
  name: string
  slug: string
  createdAt: Date
  updatedAt: Date | null
  _count: YarnsCountAggregateOutputType | null
  _min: YarnsMinAggregateOutputType | null
  _max: YarnsMaxAggregateOutputType | null
}

type GetYarnsGroupByPayload<T extends YarnsGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<YarnsGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof YarnsGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], YarnsGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], YarnsGroupByOutputType[P]>
      }
    >
  >



export type YarnsWhereInput = {
  AND?: Prisma.YarnsWhereInput | Prisma.YarnsWhereInput[]
  OR?: Prisma.YarnsWhereInput[]
  NOT?: Prisma.YarnsWhereInput | Prisma.YarnsWhereInput[]
  id?: Prisma.StringFilter<"Yarns"> | string
  name?: Prisma.StringFilter<"Yarns"> | string
  slug?: Prisma.StringFilter<"Yarns"> | string
  createdAt?: Prisma.DateTimeFilter<"Yarns"> | Date | string
  updatedAt?: Prisma.DateTimeNullableFilter<"Yarns"> | Date | string | null
}

export type YarnsOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  name?: Prisma.SortOrder
  slug?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrderInput | Prisma.SortOrder
}

export type YarnsWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  name?: string
  slug?: string
  AND?: Prisma.YarnsWhereInput | Prisma.YarnsWhereInput[]
  OR?: Prisma.YarnsWhereInput[]
  NOT?: Prisma.YarnsWhereInput | Prisma.YarnsWhereInput[]
  createdAt?: Prisma.DateTimeFilter<"Yarns"> | Date | string
  updatedAt?: Prisma.DateTimeNullableFilter<"Yarns"> | Date | string | null
}, "id" | "name" | "slug">

export type YarnsOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  name?: Prisma.SortOrder
  slug?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrderInput | Prisma.SortOrder
  _count?: Prisma.YarnsCountOrderByAggregateInput
  _max?: Prisma.YarnsMaxOrderByAggregateInput
  _min?: Prisma.YarnsMinOrderByAggregateInput
}

export type YarnsScalarWhereWithAggregatesInput = {
  AND?: Prisma.YarnsScalarWhereWithAggregatesInput | Prisma.YarnsScalarWhereWithAggregatesInput[]
  OR?: Prisma.YarnsScalarWhereWithAggregatesInput[]
  NOT?: Prisma.YarnsScalarWhereWithAggregatesInput | Prisma.YarnsScalarWhereWithAggregatesInput[]
  id?: Prisma.StringWithAggregatesFilter<"Yarns"> | string
  name?: Prisma.StringWithAggregatesFilter<"Yarns"> | string
  slug?: Prisma.StringWithAggregatesFilter<"Yarns"> | string
  createdAt?: Prisma.DateTimeWithAggregatesFilter<"Yarns"> | Date | string
  updatedAt?: Prisma.DateTimeNullableWithAggregatesFilter<"Yarns"> | Date | string | null
}

export type YarnsCreateInput = {
  id?: string
  name: string
  slug: string
  createdAt?: Date | string
  updatedAt?: Date | string | null
}

export type YarnsUncheckedCreateInput = {
  id?: string
  name: string
  slug: string
  createdAt?: Date | string
  updatedAt?: Date | string | null
}

export type YarnsUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  slug?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
}

export type YarnsUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  slug?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
}

export type YarnsCreateManyInput = {
  id?: string
  name: string
  slug: string
  createdAt?: Date | string
  updatedAt?: Date | string | null
}

export type YarnsUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  slug?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
}

export type YarnsUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  slug?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
}

export type YarnsCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  name?: Prisma.SortOrder
  slug?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type YarnsMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  name?: Prisma.SortOrder
  slug?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type YarnsMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  name?: Prisma.SortOrder
  slug?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}



export type YarnsSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  name?: boolean
  slug?: boolean
  createdAt?: boolean
  updatedAt?: boolean
}, ExtArgs["result"]["yarns"]>

export type YarnsSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  name?: boolean
  slug?: boolean
  createdAt?: boolean
  updatedAt?: boolean
}, ExtArgs["result"]["yarns"]>

export type YarnsSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  name?: boolean
  slug?: boolean
  createdAt?: boolean
  updatedAt?: boolean
}, ExtArgs["result"]["yarns"]>

export type YarnsSelectScalar = {
  id?: boolean
  name?: boolean
  slug?: boolean
  createdAt?: boolean
  updatedAt?: boolean
}

export type YarnsOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "name" | "slug" | "createdAt" | "updatedAt", ExtArgs["result"]["yarns"]>

export type $YarnsPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "Yarns"
  objects: {}
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    name: string
    slug: string
    createdAt: Date
    updatedAt: Date | null
  }, ExtArgs["result"]["yarns"]>
  composites: {}
}

export type YarnsGetPayload<S extends boolean | null | undefined | YarnsDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$YarnsPayload, S>

export type YarnsCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<YarnsFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: YarnsCountAggregateInputType | true
  }

export interface YarnsDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['Yarns'], meta: { name: 'Yarns' } }
  /**
   * Find zero or one Yarns that matches the filter.
   * @param {YarnsFindUniqueArgs} args - Arguments to find a Yarns
   * @example
   * // Get one Yarns
   * const yarns = await prisma.yarns.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends YarnsFindUniqueArgs>(args: Prisma.SelectSubset<T, YarnsFindUniqueArgs<ExtArgs>>): Prisma.Prisma__YarnsClient<runtime.Types.Result.GetResult<Prisma.$YarnsPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one Yarns that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {YarnsFindUniqueOrThrowArgs} args - Arguments to find a Yarns
   * @example
   * // Get one Yarns
   * const yarns = await prisma.yarns.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends YarnsFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, YarnsFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__YarnsClient<runtime.Types.Result.GetResult<Prisma.$YarnsPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Yarns that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {YarnsFindFirstArgs} args - Arguments to find a Yarns
   * @example
   * // Get one Yarns
   * const yarns = await prisma.yarns.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends YarnsFindFirstArgs>(args?: Prisma.SelectSubset<T, YarnsFindFirstArgs<ExtArgs>>): Prisma.Prisma__YarnsClient<runtime.Types.Result.GetResult<Prisma.$YarnsPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Yarns that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {YarnsFindFirstOrThrowArgs} args - Arguments to find a Yarns
   * @example
   * // Get one Yarns
   * const yarns = await prisma.yarns.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends YarnsFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, YarnsFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__YarnsClient<runtime.Types.Result.GetResult<Prisma.$YarnsPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more Yarns that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {YarnsFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all Yarns
   * const yarns = await prisma.yarns.findMany()
   * 
   * // Get first 10 Yarns
   * const yarns = await prisma.yarns.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const yarnsWithIdOnly = await prisma.yarns.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends YarnsFindManyArgs>(args?: Prisma.SelectSubset<T, YarnsFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$YarnsPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a Yarns.
   * @param {YarnsCreateArgs} args - Arguments to create a Yarns.
   * @example
   * // Create one Yarns
   * const Yarns = await prisma.yarns.create({
   *   data: {
   *     // ... data to create a Yarns
   *   }
   * })
   * 
   */
  create<T extends YarnsCreateArgs>(args: Prisma.SelectSubset<T, YarnsCreateArgs<ExtArgs>>): Prisma.Prisma__YarnsClient<runtime.Types.Result.GetResult<Prisma.$YarnsPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many Yarns.
   * @param {YarnsCreateManyArgs} args - Arguments to create many Yarns.
   * @example
   * // Create many Yarns
   * const yarns = await prisma.yarns.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends YarnsCreateManyArgs>(args?: Prisma.SelectSubset<T, YarnsCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many Yarns and returns the data saved in the database.
   * @param {YarnsCreateManyAndReturnArgs} args - Arguments to create many Yarns.
   * @example
   * // Create many Yarns
   * const yarns = await prisma.yarns.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many Yarns and only return the `id`
   * const yarnsWithIdOnly = await prisma.yarns.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends YarnsCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, YarnsCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$YarnsPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a Yarns.
   * @param {YarnsDeleteArgs} args - Arguments to delete one Yarns.
   * @example
   * // Delete one Yarns
   * const Yarns = await prisma.yarns.delete({
   *   where: {
   *     // ... filter to delete one Yarns
   *   }
   * })
   * 
   */
  delete<T extends YarnsDeleteArgs>(args: Prisma.SelectSubset<T, YarnsDeleteArgs<ExtArgs>>): Prisma.Prisma__YarnsClient<runtime.Types.Result.GetResult<Prisma.$YarnsPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one Yarns.
   * @param {YarnsUpdateArgs} args - Arguments to update one Yarns.
   * @example
   * // Update one Yarns
   * const yarns = await prisma.yarns.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends YarnsUpdateArgs>(args: Prisma.SelectSubset<T, YarnsUpdateArgs<ExtArgs>>): Prisma.Prisma__YarnsClient<runtime.Types.Result.GetResult<Prisma.$YarnsPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more Yarns.
   * @param {YarnsDeleteManyArgs} args - Arguments to filter Yarns to delete.
   * @example
   * // Delete a few Yarns
   * const { count } = await prisma.yarns.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends YarnsDeleteManyArgs>(args?: Prisma.SelectSubset<T, YarnsDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Yarns.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {YarnsUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many Yarns
   * const yarns = await prisma.yarns.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends YarnsUpdateManyArgs>(args: Prisma.SelectSubset<T, YarnsUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Yarns and returns the data updated in the database.
   * @param {YarnsUpdateManyAndReturnArgs} args - Arguments to update many Yarns.
   * @example
   * // Update many Yarns
   * const yarns = await prisma.yarns.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more Yarns and only return the `id`
   * const yarnsWithIdOnly = await prisma.yarns.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends YarnsUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, YarnsUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$YarnsPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one Yarns.
   * @param {YarnsUpsertArgs} args - Arguments to update or create a Yarns.
   * @example
   * // Update or create a Yarns
   * const yarns = await prisma.yarns.upsert({
   *   create: {
   *     // ... data to create a Yarns
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the Yarns we want to update
   *   }
   * })
   */
  upsert<T extends YarnsUpsertArgs>(args: Prisma.SelectSubset<T, YarnsUpsertArgs<ExtArgs>>): Prisma.Prisma__YarnsClient<runtime.Types.Result.GetResult<Prisma.$YarnsPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of Yarns.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {YarnsCountArgs} args - Arguments to filter Yarns to count.
   * @example
   * // Count the number of Yarns
   * const count = await prisma.yarns.count({
   *   where: {
   *     // ... the filter for the Yarns we want to count
   *   }
   * })
  **/
  count<T extends YarnsCountArgs>(
    args?: Prisma.Subset<T, YarnsCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], YarnsCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a Yarns.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {YarnsAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends YarnsAggregateArgs>(args: Prisma.Subset<T, YarnsAggregateArgs>): Prisma.PrismaPromise<GetYarnsAggregateType<T>>

  /**
   * Group by Yarns.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {YarnsGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends YarnsGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: YarnsGroupByArgs['orderBy'] }
      : { orderBy?: YarnsGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, YarnsGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetYarnsGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the Yarns model
 */
readonly fields: YarnsFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for Yarns.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__YarnsClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the Yarns model
 */
export interface YarnsFieldRefs {
  readonly id: Prisma.FieldRef<"Yarns", 'String'>
  readonly name: Prisma.FieldRef<"Yarns", 'String'>
  readonly slug: Prisma.FieldRef<"Yarns", 'String'>
  readonly createdAt: Prisma.FieldRef<"Yarns", 'DateTime'>
  readonly updatedAt: Prisma.FieldRef<"Yarns", 'DateTime'>
}
    

// Custom InputTypes
/**
 * Yarns findUnique
 */
export type YarnsFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Yarns
   */
  select?: Prisma.YarnsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Yarns
   */
  omit?: Prisma.YarnsOmit<ExtArgs> | null
  /**
   * Filter, which Yarns to fetch.
   */
  where: Prisma.YarnsWhereUniqueInput
}

/**
 * Yarns findUniqueOrThrow
 */
export type YarnsFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Yarns
   */
  select?: Prisma.YarnsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Yarns
   */
  omit?: Prisma.YarnsOmit<ExtArgs> | null
  /**
   * Filter, which Yarns to fetch.
   */
  where: Prisma.YarnsWhereUniqueInput
}

/**
 * Yarns findFirst
 */
export type YarnsFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Yarns
   */
  select?: Prisma.YarnsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Yarns
   */
  omit?: Prisma.YarnsOmit<ExtArgs> | null
  /**
   * Filter, which Yarns to fetch.
   */
  where?: Prisma.YarnsWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Yarns to fetch.
   */
  orderBy?: Prisma.YarnsOrderByWithRelationInput | Prisma.YarnsOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for Yarns.
   */
  cursor?: Prisma.YarnsWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Yarns from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Yarns.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Yarns.
   */
  distinct?: Prisma.YarnsScalarFieldEnum | Prisma.YarnsScalarFieldEnum[]
}

/**
 * Yarns findFirstOrThrow
 */
export type YarnsFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Yarns
   */
  select?: Prisma.YarnsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Yarns
   */
  omit?: Prisma.YarnsOmit<ExtArgs> | null
  /**
   * Filter, which Yarns to fetch.
   */
  where?: Prisma.YarnsWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Yarns to fetch.
   */
  orderBy?: Prisma.YarnsOrderByWithRelationInput | Prisma.YarnsOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for Yarns.
   */
  cursor?: Prisma.YarnsWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Yarns from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Yarns.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Yarns.
   */
  distinct?: Prisma.YarnsScalarFieldEnum | Prisma.YarnsScalarFieldEnum[]
}

/**
 * Yarns findMany
 */
export type YarnsFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Yarns
   */
  select?: Prisma.YarnsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Yarns
   */
  omit?: Prisma.YarnsOmit<ExtArgs> | null
  /**
   * Filter, which Yarns to fetch.
   */
  where?: Prisma.YarnsWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Yarns to fetch.
   */
  orderBy?: Prisma.YarnsOrderByWithRelationInput | Prisma.YarnsOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing Yarns.
   */
  cursor?: Prisma.YarnsWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Yarns from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Yarns.
   */
  skip?: number
  distinct?: Prisma.YarnsScalarFieldEnum | Prisma.YarnsScalarFieldEnum[]
}

/**
 * Yarns create
 */
export type YarnsCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Yarns
   */
  select?: Prisma.YarnsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Yarns
   */
  omit?: Prisma.YarnsOmit<ExtArgs> | null
  /**
   * The data needed to create a Yarns.
   */
  data: Prisma.XOR<Prisma.YarnsCreateInput, Prisma.YarnsUncheckedCreateInput>
}

/**
 * Yarns createMany
 */
export type YarnsCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many Yarns.
   */
  data: Prisma.YarnsCreateManyInput | Prisma.YarnsCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * Yarns createManyAndReturn
 */
export type YarnsCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Yarns
   */
  select?: Prisma.YarnsSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the Yarns
   */
  omit?: Prisma.YarnsOmit<ExtArgs> | null
  /**
   * The data used to create many Yarns.
   */
  data: Prisma.YarnsCreateManyInput | Prisma.YarnsCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * Yarns update
 */
export type YarnsUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Yarns
   */
  select?: Prisma.YarnsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Yarns
   */
  omit?: Prisma.YarnsOmit<ExtArgs> | null
  /**
   * The data needed to update a Yarns.
   */
  data: Prisma.XOR<Prisma.YarnsUpdateInput, Prisma.YarnsUncheckedUpdateInput>
  /**
   * Choose, which Yarns to update.
   */
  where: Prisma.YarnsWhereUniqueInput
}

/**
 * Yarns updateMany
 */
export type YarnsUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update Yarns.
   */
  data: Prisma.XOR<Prisma.YarnsUpdateManyMutationInput, Prisma.YarnsUncheckedUpdateManyInput>
  /**
   * Filter which Yarns to update
   */
  where?: Prisma.YarnsWhereInput
  /**
   * Limit how many Yarns to update.
   */
  limit?: number
}

/**
 * Yarns updateManyAndReturn
 */
export type YarnsUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Yarns
   */
  select?: Prisma.YarnsSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the Yarns
   */
  omit?: Prisma.YarnsOmit<ExtArgs> | null
  /**
   * The data used to update Yarns.
   */
  data: Prisma.XOR<Prisma.YarnsUpdateManyMutationInput, Prisma.YarnsUncheckedUpdateManyInput>
  /**
   * Filter which Yarns to update
   */
  where?: Prisma.YarnsWhereInput
  /**
   * Limit how many Yarns to update.
   */
  limit?: number
}

/**
 * Yarns upsert
 */
export type YarnsUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Yarns
   */
  select?: Prisma.YarnsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Yarns
   */
  omit?: Prisma.YarnsOmit<ExtArgs> | null
  /**
   * The filter to search for the Yarns to update in case it exists.
   */
  where: Prisma.YarnsWhereUniqueInput
  /**
   * In case the Yarns found by the `where` argument doesn't exist, create a new Yarns with this data.
   */
  create: Prisma.XOR<Prisma.YarnsCreateInput, Prisma.YarnsUncheckedCreateInput>
  /**
   * In case the Yarns was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.YarnsUpdateInput, Prisma.YarnsUncheckedUpdateInput>
}

/**
 * Yarns delete
 */
export type YarnsDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Yarns
   */
  select?: Prisma.YarnsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Yarns
   */
  omit?: Prisma.YarnsOmit<ExtArgs> | null
  /**
   * Filter which Yarns to delete.
   */
  where: Prisma.YarnsWhereUniqueInput
}

/**
 * Yarns deleteMany
 */
export type YarnsDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which Yarns to delete
   */
  where?: Prisma.YarnsWhereInput
  /**
   * Limit how many Yarns to delete.
   */
  limit?: number
}

/**
 * Yarns without action
 */
export type YarnsDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Yarns
   */
  select?: Prisma.YarnsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Yarns
   */
  omit?: Prisma.YarnsOmit<ExtArgs> | null
}
