
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * WARNING: This is an internal file that is subject to change!
 *
 * 🛑 Under no circumstances should you import this file directly! 🛑
 *
 * All exports from this file are wrapped under a `Prisma` namespace object in the browser.ts file.
 * While this enables partial backward compatibility, it is not part of the stable public API.
 *
 * If you are looking for your Models, Enums, and Input Types, please import them from the respective
 * model files in the `model` directory!
 */

import * as runtime from "@prisma/client/runtime/index-browser"

export type * from '../models.ts'
export type * from './prismaNamespace.ts'

export const Decimal = runtime.Decimal


export const NullTypes = {
  DbNull: runtime.NullTypes.DbNull as (new (secret: never) => typeof runtime.DbNull),
  JsonNull: runtime.NullTypes.JsonNull as (new (secret: never) => typeof runtime.JsonNull),
  AnyNull: runtime.NullTypes.AnyNull as (new (secret: never) => typeof runtime.AnyNull),
}
/**
 * Helper for filtering JSON entries that have `null` on the database (empty on the db)
 *
 * @see https://www.prisma.io/docs/concepts/components/prisma-client/working-with-fields/working-with-json-fields#filtering-on-a-json-field
 */
export const DbNull = runtime.DbNull

/**
 * Helper for filtering JSON entries that have JSON `null` values (not empty on the db)
 *
 * @see https://www.prisma.io/docs/concepts/components/prisma-client/working-with-fields/working-with-json-fields#filtering-on-a-json-field
 */
export const JsonNull = runtime.JsonNull

/**
 * Helper for filtering JSON entries that are `Prisma.DbNull` or `Prisma.JsonNull`
 *
 * @see https://www.prisma.io/docs/concepts/components/prisma-client/working-with-fields/working-with-json-fields#filtering-on-a-json-field
 */
export const AnyNull = runtime.AnyNull


export const ModelName = {
  Color: 'Color',
  ColorLayout: 'ColorLayout',
  ColorPosition: 'ColorPosition',
  Fabric: 'Fabric',
  FabricSpec: 'FabricSpec',
  FabricConstruction: 'FabricConstruction',
  WeavingMachine: 'WeavingMachine',
  Yarn: 'Yarn'
} as const

export type ModelName = (typeof ModelName)[keyof typeof ModelName]

/*
 * Enums
 */

export const TransactionIsolationLevel = runtime.makeStrictEnum({
  ReadUncommitted: 'ReadUncommitted',
  ReadCommitted: 'ReadCommitted',
  RepeatableRead: 'RepeatableRead',
  Serializable: 'Serializable'
} as const)

export type TransactionIsolationLevel = (typeof TransactionIsolationLevel)[keyof typeof TransactionIsolationLevel]


export const ColorScalarFieldEnum = {
  id: 'id',
  name: 'name',
  slug: 'slug',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
} as const

export type ColorScalarFieldEnum = (typeof ColorScalarFieldEnum)[keyof typeof ColorScalarFieldEnum]


export const ColorLayoutScalarFieldEnum = {
  id: 'id',
  fabricId: 'fabricId',
  colorContent: 'colorContent',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
} as const

export type ColorLayoutScalarFieldEnum = (typeof ColorLayoutScalarFieldEnum)[keyof typeof ColorLayoutScalarFieldEnum]


export const ColorPositionScalarFieldEnum = {
  id: 'id',
  fabricId: 'fabricId',
  colorLayoutId: 'colorLayoutId',
  fabricContent: 'fabricContent',
  wbNo: 'wbNo',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
} as const

export type ColorPositionScalarFieldEnum = (typeof ColorPositionScalarFieldEnum)[keyof typeof ColorPositionScalarFieldEnum]


export const FabricScalarFieldEnum = {
  id: 'id',
  name: 'name',
  slug: 'slug',
  hasColor: 'hasColor',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
} as const

export type FabricScalarFieldEnum = (typeof FabricScalarFieldEnum)[keyof typeof FabricScalarFieldEnum]


export const FabricSpecScalarFieldEnum = {
  id: 'id',
  fabricId: 'fabricId',
  width: 'width',
  length: 'length',
  warpYarnId: 'warpYarnId',
  weftYarnId: 'weftYarnId',
  color: 'color',
  cutmarkPerRoll: 'cutmarkPerRoll',
  totalEnds: 'totalEnds',
  reedWidth: 'reedWidth',
  reedNo: 'reedNo',
  fringe: 'fringe',
  pickPerInch: 'pickPerInch',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
} as const

export type FabricSpecScalarFieldEnum = (typeof FabricSpecScalarFieldEnum)[keyof typeof FabricSpecScalarFieldEnum]


export const FabricConstructionScalarFieldEnum = {
  id: 'id',
  constructionNo: 'constructionNo',
  fabricSpecId: 'fabricSpecId',
  rollCount: 'rollCount',
  warpingMachine: 'warpingMachine',
  coneCount: 'coneCount',
  sectionCount: 'sectionCount',
  sectionLength: 'sectionLength',
  beamWidth: 'beamWidth',
  spareEnds: 'spareEnds',
  beamingLoss: 'beamingLoss',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
} as const

export type FabricConstructionScalarFieldEnum = (typeof FabricConstructionScalarFieldEnum)[keyof typeof FabricConstructionScalarFieldEnum]


export const WeavingMachineScalarFieldEnum = {
  id: 'id',
  name: 'name',
  slug: 'slug',
  width: 'width',
  type: 'type',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
} as const

export type WeavingMachineScalarFieldEnum = (typeof WeavingMachineScalarFieldEnum)[keyof typeof WeavingMachineScalarFieldEnum]


export const YarnScalarFieldEnum = {
  id: 'id',
  name: 'name',
  slug: 'slug',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
} as const

export type YarnScalarFieldEnum = (typeof YarnScalarFieldEnum)[keyof typeof YarnScalarFieldEnum]


export const SortOrder = {
  asc: 'asc',
  desc: 'desc'
} as const

export type SortOrder = (typeof SortOrder)[keyof typeof SortOrder]


export const NullableJsonNullValueInput = {
  DbNull: DbNull,
  JsonNull: JsonNull
} as const

export type NullableJsonNullValueInput = (typeof NullableJsonNullValueInput)[keyof typeof NullableJsonNullValueInput]


export const JsonNullValueInput = {
  JsonNull: JsonNull
} as const

export type JsonNullValueInput = (typeof JsonNullValueInput)[keyof typeof JsonNullValueInput]


export const QueryMode = {
  default: 'default',
  insensitive: 'insensitive'
} as const

export type QueryMode = (typeof QueryMode)[keyof typeof QueryMode]


export const NullsOrder = {
  first: 'first',
  last: 'last'
} as const

export type NullsOrder = (typeof NullsOrder)[keyof typeof NullsOrder]


export const JsonNullValueFilter = {
  DbNull: DbNull,
  JsonNull: JsonNull,
  AnyNull: AnyNull
} as const

export type JsonNullValueFilter = (typeof JsonNullValueFilter)[keyof typeof JsonNullValueFilter]

