
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
* This file exports all enum related types from the schema.
*
* 🟢 You can import this file directly.
*/

export const WbMachineType = {
  BENN_KM: 'BENN_KM',
  MO_TS: 'MO_TS'
} as const

export type WbMachineType = (typeof WbMachineType)[keyof typeof WbMachineType]


export const WbProcessType = {
  WARPING: 'WARPING',
  BEAMING: 'BEAMING'
} as const

export type WbProcessType = (typeof WbProcessType)[keyof typeof WbProcessType]
