
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
* This file exports all enum related types from the schema.
*
* 🟢 You can import this file directly.
*/

export const MachineType = {
  BENNINGER: 'BENNINGER',
  KARL_MAYER: 'KARL_MAYER',
  W_MO: 'W_MO',
  W_TSUDAKOMA: 'W_TSUDAKOMA'
} as const

export type MachineType = (typeof MachineType)[keyof typeof MachineType]


export const ProcessType = {
  WARPING: 'WARPING',
  BEAMING: 'BEAMING'
} as const

export type ProcessType = (typeof ProcessType)[keyof typeof ProcessType]
