/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as GuestRouteRouteImport } from './routes/_guest/route'
import { Route as AuthRouteRouteImport } from './routes/_auth/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as GuestSignInRouteImport } from './routes/_guest/sign-in'
import { Route as AuthDashboardRouteImport } from './routes/_auth/dashboard'
import { Route as AuthColorRouteImport } from './routes/_auth/color'
import { Route as AuthFabricsIndexRouteImport } from './routes/_auth/fabrics/index'
import { Route as AuthColorPositionsIndexRouteImport } from './routes/_auth/color-positions/index'
import { Route as AuthColorLayoutsIndexRouteImport } from './routes/_auth/color-layouts/index'
import { Route as AuthColorLayoutsAddNewRouteImport } from './routes/_auth/color-layouts/add-new'
import { Route as AuthColorPositionsColorPositionIdIndexRouteImport } from './routes/_auth/color-positions/$colorPositionId/index'
import { Route as AuthColorLayoutsColorLayoutIdIndexRouteImport } from './routes/_auth/color-layouts/$colorLayoutId/index'
import { Route as AuthColorPositionsColorPositionIdEditRouteImport } from './routes/_auth/color-positions/$colorPositionId/edit'
import { Route as AuthColorLayoutsColorLayoutIdEditRouteImport } from './routes/_auth/color-layouts/$colorLayoutId/edit'

const GuestRouteRoute = GuestRouteRouteImport.update({
  id: '/_guest',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRouteRoute = AuthRouteRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const GuestSignInRoute = GuestSignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => GuestRouteRoute,
} as any)
const AuthDashboardRoute = AuthDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthColorRoute = AuthColorRouteImport.update({
  id: '/color',
  path: '/color',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthFabricsIndexRoute = AuthFabricsIndexRouteImport.update({
  id: '/fabrics/',
  path: '/fabrics/',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthColorPositionsIndexRoute = AuthColorPositionsIndexRouteImport.update({
  id: '/color-positions/',
  path: '/color-positions/',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthColorLayoutsIndexRoute = AuthColorLayoutsIndexRouteImport.update({
  id: '/color-layouts/',
  path: '/color-layouts/',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthColorLayoutsAddNewRoute = AuthColorLayoutsAddNewRouteImport.update({
  id: '/color-layouts/add-new',
  path: '/color-layouts/add-new',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthColorPositionsColorPositionIdIndexRoute =
  AuthColorPositionsColorPositionIdIndexRouteImport.update({
    id: '/color-positions/$colorPositionId/',
    path: '/color-positions/$colorPositionId/',
    getParentRoute: () => AuthRouteRoute,
  } as any)
const AuthColorLayoutsColorLayoutIdIndexRoute =
  AuthColorLayoutsColorLayoutIdIndexRouteImport.update({
    id: '/color-layouts/$colorLayoutId/',
    path: '/color-layouts/$colorLayoutId/',
    getParentRoute: () => AuthRouteRoute,
  } as any)
const AuthColorPositionsColorPositionIdEditRoute =
  AuthColorPositionsColorPositionIdEditRouteImport.update({
    id: '/color-positions/$colorPositionId/edit',
    path: '/color-positions/$colorPositionId/edit',
    getParentRoute: () => AuthRouteRoute,
  } as any)
const AuthColorLayoutsColorLayoutIdEditRoute =
  AuthColorLayoutsColorLayoutIdEditRouteImport.update({
    id: '/color-layouts/$colorLayoutId/edit',
    path: '/color-layouts/$colorLayoutId/edit',
    getParentRoute: () => AuthRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/color': typeof AuthColorRoute
  '/dashboard': typeof AuthDashboardRoute
  '/sign-in': typeof GuestSignInRoute
  '/color-layouts/add-new': typeof AuthColorLayoutsAddNewRoute
  '/color-layouts/': typeof AuthColorLayoutsIndexRoute
  '/color-positions/': typeof AuthColorPositionsIndexRoute
  '/fabrics/': typeof AuthFabricsIndexRoute
  '/color-layouts/$colorLayoutId/edit': typeof AuthColorLayoutsColorLayoutIdEditRoute
  '/color-positions/$colorPositionId/edit': typeof AuthColorPositionsColorPositionIdEditRoute
  '/color-layouts/$colorLayoutId/': typeof AuthColorLayoutsColorLayoutIdIndexRoute
  '/color-positions/$colorPositionId/': typeof AuthColorPositionsColorPositionIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/color': typeof AuthColorRoute
  '/dashboard': typeof AuthDashboardRoute
  '/sign-in': typeof GuestSignInRoute
  '/color-layouts/add-new': typeof AuthColorLayoutsAddNewRoute
  '/color-layouts': typeof AuthColorLayoutsIndexRoute
  '/color-positions': typeof AuthColorPositionsIndexRoute
  '/fabrics': typeof AuthFabricsIndexRoute
  '/color-layouts/$colorLayoutId/edit': typeof AuthColorLayoutsColorLayoutIdEditRoute
  '/color-positions/$colorPositionId/edit': typeof AuthColorPositionsColorPositionIdEditRoute
  '/color-layouts/$colorLayoutId': typeof AuthColorLayoutsColorLayoutIdIndexRoute
  '/color-positions/$colorPositionId': typeof AuthColorPositionsColorPositionIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_auth': typeof AuthRouteRouteWithChildren
  '/_guest': typeof GuestRouteRouteWithChildren
  '/_auth/color': typeof AuthColorRoute
  '/_auth/dashboard': typeof AuthDashboardRoute
  '/_guest/sign-in': typeof GuestSignInRoute
  '/_auth/color-layouts/add-new': typeof AuthColorLayoutsAddNewRoute
  '/_auth/color-layouts/': typeof AuthColorLayoutsIndexRoute
  '/_auth/color-positions/': typeof AuthColorPositionsIndexRoute
  '/_auth/fabrics/': typeof AuthFabricsIndexRoute
  '/_auth/color-layouts/$colorLayoutId/edit': typeof AuthColorLayoutsColorLayoutIdEditRoute
  '/_auth/color-positions/$colorPositionId/edit': typeof AuthColorPositionsColorPositionIdEditRoute
  '/_auth/color-layouts/$colorLayoutId/': typeof AuthColorLayoutsColorLayoutIdIndexRoute
  '/_auth/color-positions/$colorPositionId/': typeof AuthColorPositionsColorPositionIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/color'
    | '/dashboard'
    | '/sign-in'
    | '/color-layouts/add-new'
    | '/color-layouts/'
    | '/color-positions/'
    | '/fabrics/'
    | '/color-layouts/$colorLayoutId/edit'
    | '/color-positions/$colorPositionId/edit'
    | '/color-layouts/$colorLayoutId/'
    | '/color-positions/$colorPositionId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/color'
    | '/dashboard'
    | '/sign-in'
    | '/color-layouts/add-new'
    | '/color-layouts'
    | '/color-positions'
    | '/fabrics'
    | '/color-layouts/$colorLayoutId/edit'
    | '/color-positions/$colorPositionId/edit'
    | '/color-layouts/$colorLayoutId'
    | '/color-positions/$colorPositionId'
  id:
    | '__root__'
    | '/'
    | '/_auth'
    | '/_guest'
    | '/_auth/color'
    | '/_auth/dashboard'
    | '/_guest/sign-in'
    | '/_auth/color-layouts/add-new'
    | '/_auth/color-layouts/'
    | '/_auth/color-positions/'
    | '/_auth/fabrics/'
    | '/_auth/color-layouts/$colorLayoutId/edit'
    | '/_auth/color-positions/$colorPositionId/edit'
    | '/_auth/color-layouts/$colorLayoutId/'
    | '/_auth/color-positions/$colorPositionId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRouteRoute: typeof AuthRouteRouteWithChildren
  GuestRouteRoute: typeof GuestRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_guest': {
      id: '/_guest'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof GuestRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_guest/sign-in': {
      id: '/_guest/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof GuestSignInRouteImport
      parentRoute: typeof GuestRouteRoute
    }
    '/_auth/dashboard': {
      id: '/_auth/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthDashboardRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/color': {
      id: '/_auth/color'
      path: '/color'
      fullPath: '/color'
      preLoaderRoute: typeof AuthColorRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/fabrics/': {
      id: '/_auth/fabrics/'
      path: '/fabrics'
      fullPath: '/fabrics/'
      preLoaderRoute: typeof AuthFabricsIndexRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/color-positions/': {
      id: '/_auth/color-positions/'
      path: '/color-positions'
      fullPath: '/color-positions/'
      preLoaderRoute: typeof AuthColorPositionsIndexRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/color-layouts/': {
      id: '/_auth/color-layouts/'
      path: '/color-layouts'
      fullPath: '/color-layouts/'
      preLoaderRoute: typeof AuthColorLayoutsIndexRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/color-layouts/add-new': {
      id: '/_auth/color-layouts/add-new'
      path: '/color-layouts/add-new'
      fullPath: '/color-layouts/add-new'
      preLoaderRoute: typeof AuthColorLayoutsAddNewRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/color-positions/$colorPositionId/': {
      id: '/_auth/color-positions/$colorPositionId/'
      path: '/color-positions/$colorPositionId'
      fullPath: '/color-positions/$colorPositionId/'
      preLoaderRoute: typeof AuthColorPositionsColorPositionIdIndexRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/color-layouts/$colorLayoutId/': {
      id: '/_auth/color-layouts/$colorLayoutId/'
      path: '/color-layouts/$colorLayoutId'
      fullPath: '/color-layouts/$colorLayoutId/'
      preLoaderRoute: typeof AuthColorLayoutsColorLayoutIdIndexRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/color-positions/$colorPositionId/edit': {
      id: '/_auth/color-positions/$colorPositionId/edit'
      path: '/color-positions/$colorPositionId/edit'
      fullPath: '/color-positions/$colorPositionId/edit'
      preLoaderRoute: typeof AuthColorPositionsColorPositionIdEditRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/color-layouts/$colorLayoutId/edit': {
      id: '/_auth/color-layouts/$colorLayoutId/edit'
      path: '/color-layouts/$colorLayoutId/edit'
      fullPath: '/color-layouts/$colorLayoutId/edit'
      preLoaderRoute: typeof AuthColorLayoutsColorLayoutIdEditRouteImport
      parentRoute: typeof AuthRouteRoute
    }
  }
}

interface AuthRouteRouteChildren {
  AuthColorRoute: typeof AuthColorRoute
  AuthDashboardRoute: typeof AuthDashboardRoute
  AuthColorLayoutsAddNewRoute: typeof AuthColorLayoutsAddNewRoute
  AuthColorLayoutsIndexRoute: typeof AuthColorLayoutsIndexRoute
  AuthColorPositionsIndexRoute: typeof AuthColorPositionsIndexRoute
  AuthFabricsIndexRoute: typeof AuthFabricsIndexRoute
  AuthColorLayoutsColorLayoutIdEditRoute: typeof AuthColorLayoutsColorLayoutIdEditRoute
  AuthColorPositionsColorPositionIdEditRoute: typeof AuthColorPositionsColorPositionIdEditRoute
  AuthColorLayoutsColorLayoutIdIndexRoute: typeof AuthColorLayoutsColorLayoutIdIndexRoute
  AuthColorPositionsColorPositionIdIndexRoute: typeof AuthColorPositionsColorPositionIdIndexRoute
}

const AuthRouteRouteChildren: AuthRouteRouteChildren = {
  AuthColorRoute: AuthColorRoute,
  AuthDashboardRoute: AuthDashboardRoute,
  AuthColorLayoutsAddNewRoute: AuthColorLayoutsAddNewRoute,
  AuthColorLayoutsIndexRoute: AuthColorLayoutsIndexRoute,
  AuthColorPositionsIndexRoute: AuthColorPositionsIndexRoute,
  AuthFabricsIndexRoute: AuthFabricsIndexRoute,
  AuthColorLayoutsColorLayoutIdEditRoute:
    AuthColorLayoutsColorLayoutIdEditRoute,
  AuthColorPositionsColorPositionIdEditRoute:
    AuthColorPositionsColorPositionIdEditRoute,
  AuthColorLayoutsColorLayoutIdIndexRoute:
    AuthColorLayoutsColorLayoutIdIndexRoute,
  AuthColorPositionsColorPositionIdIndexRoute:
    AuthColorPositionsColorPositionIdIndexRoute,
}

const AuthRouteRouteWithChildren = AuthRouteRoute._addFileChildren(
  AuthRouteRouteChildren,
)

interface GuestRouteRouteChildren {
  GuestSignInRoute: typeof GuestSignInRoute
}

const GuestRouteRouteChildren: GuestRouteRouteChildren = {
  GuestSignInRoute: GuestSignInRoute,
}

const GuestRouteRouteWithChildren = GuestRouteRoute._addFileChildren(
  GuestRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRouteRoute: AuthRouteRouteWithChildren,
  GuestRouteRoute: GuestRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
